= {project-title}

== Introduction

{project-title} is a data generator for Redis.

It supports https://redis.io[Redis] and https://redis.com/redis-enterprise-software/overview/[Redis Enterprise] in either standalone or https://redis.io/topics/cluster-tutorial[cluster] deployments.

[[_getting-started]]
== Getting Started

include::{includedir}/_getting-started.adoc[leveloffset=+1]

== Random Data-Structure Generator

The `ds` subcommand generates random data for Redis data-structures (set, list, zset, stream, string, hash), RedisJSON, and RedisTimeSeries.

=== Usage

[subs=+quotes]
----
[green]#riot-gen# -h <host> -p <port> ds [OPTIONS]
----

== Faker Generator

The `faker` subcommand generates data using https://github.com/DiUS/java-faker[Faker] and writes it to Redis.

=== Usage

[subs=+quotes]
----
[green]#riot-gen# -h <host> -p <port> faker [olive]#SPEL#... [REDIS COMMAND...]
----

where SPEL is a https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions[Spring Expression Language] field in the form `field="expression"`.

To show the full usage, run:

[subs="+quotes"]
----
[green]#riot-gen# faker --help
----

.Hash generator example
[source,console]
----
include::{test-resources}/faker-hset[]
----

.Set generator example
[source,console]
----
include::{test-resources}/faker-sadd[]
----

=== Redis Commands

include::{includedir}/_redis-commands.adoc[leveloffset=+2]

=== Processing

include::{includedir}/_processing.adoc[leveloffset=+2]

=== RediSearch

You can infer generator fields from a RediSearch index using the `--infer` option:

[source,console]
----
include::{test-resources}/faker-infer[]
----

[[_faker_fields]]
== Faker Fields

Run this command to display the list of available Faker providers:

[subs="+quotes"]
----
[green]#riot-gen# faker-help
----

Most providers don't take any arguments and can be called directly, for example:

[subs="+quotes"]
----
[green]#riot-gen# faker firstName="name.firstName"
----

Some providers take parameters, for example:
[subs="+quotes"]
----
[green]#riot-gen# faker lease="number.digits(2)"
----

Refer to the link specified for each provider for complete documentation.

== Architecture

include::{includedir}/_architecture.adoc[leveloffset=+1]
