= {project-title}

== Introduction

{project-title} is a data generator for Redis based on https://github.com/DiUS/java-faker[Faker].

It supports https://redis.io[Redis] and https://redis.com/redis-enterprise-software/overview/[Redis Enterprise] in either standalone or https://redis.io/topics/cluster-tutorial[cluster] deployments.

include::{includedir}/getting-started.adoc[leveloffset=+1]

== Importing

The `import` command generates data and writes it to Redis. The general usage is:

[subs=+quotes]
....
[green]#riot-gen# -h <host> -p <port> import [olive]#SPEL#... [REDIS COMMAND...]
....

where SPEL is a https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions[Spring Expression Language] field in the form `field="expression"`.

To show the full usage, run:

[subs="+quotes"]
....
[green]#riot-gen# import --help
....

.Hash generator example
[source,console]
----
include::{test-resources}/import-hset[]
----

.Set generator example
[source,console]
----
include::{test-resources}/import-sadd[]
----

include::{includedir}/redis-commands.adoc[leveloffset=+2]

include::{includedir}/processing.adoc[leveloffset=+2]

=== RediSearch

You can infer generator fields from a RediSearch index using the `--infer` option:

[source,console]
----
include::{test-resources}/import-infer[]
----

[[_faker_fields]]
== Faker Fields

Run this command to display the list of available Faker providers:

[subs="+quotes"]
....
[green]#riot-gen# faker-help
....

Most providers don't take any arguments and can be called directly, for example:

[subs="+quotes"]
....
[green]#riot-gen# import firstName="name.firstName"
....

Some providers take parameters, for example:
[subs="+quotes"]
....
[green]#riot-gen# import lease="number.digits(2)"
....

Refer to the link specified for each provider for complete documentation.
