[[_databases]]
= Databases

{project-title} can import from and export to databases.

[[_database_drivers]]
== Drivers
{project-title} relies on JDBC to interact with databases.
It includes JDBC drivers for the most common database systems:

* {link_jdbc_oracle}
+
`jdbc:oracle:thin:@myhost:1521:orcl`

* {link_jdbc_db2}
+
`jdbc:db2://host:port/database`

* {link_jdbc_mssql}
+
`jdbc:sqlserver://[serverName[\instanceName][:portNumber]][;property=value[;property=value]]`

* {link_jdbc_mysql}
+
`jdbc:mysql://[host]:[port][/database][?properties]`

* {link_jdbc_postgres}
+
`jdbc:postgresql://host:port/database`

* {link_jdbc_sqlite}
+
`jdbc:sqlite:sqlite_database_file_path`

[TIP]
====
For non-included databases you must install the corresponding JDBC driver under the `lib` directory and modify the `CLASSPATH`:

* *nix: `bin/riot` -> `CLASSPATH=$APP_HOME/lib/myjdbc.jar:$APP_HOME/lib/...`
* Windows: `bin\riot.bat` -> `set CLASSPATH=%APP_HOME%\lib\myjdbc.jar;%APP_HOME%\lib\...`
====

:leveloffset: 2
include::{includedir}/db-import.adoc[]
include::{includedir}/db-export.adoc[]
:leveloffset: 1
