[[_db]]
= Databases

{project-title} includes two commands for interaction with relational databases:

<<_db_import, `db-import`>>:: Import database tables into Redis
<<_db_export, `db-export`>>:: Export Redis data structures to a database

[[_db_drivers]]
== Drivers

{project-title} relies on JDBC to interact with databases.
It includes JDBC drivers for the most common database systems:

https://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/OracleDriver.html[Oracle]:: `jdbc:oracle:thin:@myhost:1521:orcl`

https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-2017[SQL Server]:: `jdbc:sqlserver://[serverName[\instanceName][:portNumber]][;property=value[;property=value]]`

https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html[MySQL]:: `jdbc:mysql://[host]:[port][/database][?properties]`

https://www.postgresql.org/docs/7.4/jdbc-use.html[Postgres]:: `jdbc:postgresql://host:port/database`

[TIP]
====
For non-included databases you must install the corresponding JDBC driver under the `lib` directory and modify the `CLASSPATH`:

*nix:: `bin/riot` -> `CLASSPATH=$APP_HOME/lib/myjdbc.jar:$APP_HOME/lib/...`
Windows:: `bin\riot.bat` -> `set CLASSPATH=%APP_HOME%\lib\myjdbc.jar;%APP_HOME%\lib\...`
====

[[_db_import]]
== Database Import

The `db-import` command imports data from a relational database into Redis.

NOTE: Ensure {project-title} has the relevant JDBC driver for your database.
See the <<_db_drivers,Drivers>> section for more details.

[source,console]
----
riot db-import --jdbc-url <jdbc url> --uri <redis uri> SQL [REDIS COMMAND...]
----

To show the full usage, run:

[source,console]
----
riot db-import --help
----

You must specify at least one Redis command as a target.

IMPORTANT: Redis connection options apply to the root command (`riot`) and not to subcommands.

The keys that will be written are constructed from input records by concatenating the keyspace prefix and key fields.

image::mapping.svg[]

.PostgreSQL Import Example
[source,console]
----
include::{testdir}/db-import-postgresql[]
----

.Import from PostgreSQL to JSON strings
[source,console]
----
include::{testdir}/db-import-postgresql-set[]
----

This will produce Redis strings that look like this:
[source,json]
----
include::{includedir}/../resources/order.json[]
----

[[_db_export]]
== Database Export

Use the `db-export` command to read from a Redis database and writes to a SQL database.

NOTE: Ensure {project-title} has the relevant JDBC driver for your database.
See the <<_db_drivers,Drivers>> section for more details.

The general usage is:
[source,console]
----
riot db-export --jdbc-url <jdbc url> SQL
----

To show the full usage, run:
[source,console]
----
riot db-export --help
----

.Example: export to PostgreSQL
[source,console]
----
include::{testdir}/db-export-postgresql[]
----


