[[_datagen]]
= Data Generation

{project-title} includes 2 commands for data generation:

<<_datagen_struct,`generate`>>:: Generate Redis data structures
<<_datagen_faker,`faker`>>:: Import data from {link_datafaker}

[[_datagen_struct]]
== Data Structure Generator

The `gen` command generates Redis data structures as well as JSON and Timeseries.

[source,console]
----
riot gen [OPTIONS]
----

.Example
[source,console]
----
include::{testdir}/generate[]
----

[[_datagen_faker]]
== Faker Generator

The `faker` command generates data using {link_datafaker}.

[source,console]
----
riot faker [OPTIONS] EXPRESSION... [REDIS COMMAND...]
----

where `EXPRESSION` is a https://www.datafaker.net/documentation/expressions/[Faker expression] field in the form `field="expression"`.

To show the full usage, run:

[source,console]
----
riot faker --help
----

You must specify at least one Redis command as a target.

[IMPORTANT]
====
Redis connection options apply to the root command (`riot`) and not to subcommands.

In this example the Redis options will not be taken into account:

[source,subs="verbatim,attributes"]
----
riot faker id="numerify '####'" hset -h myredis.com -p 6380
----
====

[[_datagen_faker_keys]]
=== Keys

Keys are constructed from input records by concatenating the keyspace prefix and key fields.

image::mapping.svg[]

.Import into hashes
[source,console]
----
include::{testdir}/faker-hset[]
----

.Import into sets
[source,console]
----
include::{testdir}/faker-sadd[]
----

[[_datagen_faker_providers]]
=== Data Providers

Faker offers many data providers.
Most providers don't take any arguments and can be called directly:

.Simple Faker example
[source,console]
----
riot faker firstName="name.first_name"
----

Some providers take parameters:

.Parameter Faker example
[source,console]
----
riot faker lease="number.digits '2'"
----

Here are a few sample Faker expressions:

* `regexify '(a|b){2,3}'`
* `regexify '\\.\\*\\?\\+'`
* `bothify '????','false'`
* `name.first_name`
* `name.last_name`
* `number.number_between '1','10'`

Refer to {link_datafaker_doc} for a list of providers and their corresponding documentation.

