:ec: ElastiCache

[[_elasticache]]
= {ec} Migration

This recipe contains step-by-step instructions to migrate an {ec} (EC) database to {link_redis_cloud} or {link_redis_software}.

The following scenarios are covered:

* One-time (snapshot) migration
* Online (live) migration

IMPORTANT: It is recommended to read the <<_replication,Replication>> section to familiarize yourself with its usage and architecture.

== Setup

=== Prerequisites

For this recipe you will require the following resources:
 
* AWS {ec}: _Primary Endpoint_ in case of Single Master and _Configuration Endpoint_ in case of Clustered EC.
Refer to https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Endpoints.html[this link] to learn more
* {link_redis_cloud} or {link_redis_software}
* An Amazon EC2 instance to run {project-title}

[IMPORTANT]
.Keyspace Notifications
====
For a live migration you need to enable keyspace notifications on your {ec} instance (see {link_ec_notifications}).
====

=== Migration Host

To run the migration tool we will need an EC2 instance.

You can either create a new EC2 instance or leverage an existing one if available.
In the example below we first create an instance on AWS Cloud Platform.
The most common scenario is to access an {ec} cluster from an Amazon EC2 instance in the same Amazon Virtual Private Cloud (Amazon VPC).
We have used Ubuntu 16.04 LTS for this setup but you can choose any Ubuntu or Debian distribution of your choice.
 
SSH to this EC2 instance from your laptop:

[source,console]
----
ssh -i “public key” <AWS EC2 Instance>
----

Install `redis-cli` on this new instance by running this command:

[source,console]
----
sudo apt update
sudo apt install -y redis-tools
----

Use `redis-cli` to check connectivity with the {ec} database:

[source,console]
----
redis-cli -h <ec primary endpoint> -p 6379
----

Ensure that the above command allows you to connect to the remote {ec} database successfully.


=== Installing {project-title}

Let's install {project-title} on the EC2 instance we set up previously.
For this we'll follow the steps in <<_install_manual,Manual Installation>>.

== Performing Migration

We are now all set to begin the migration process.
The options you will use depend on your source and target databases, as well as the replication mode (snapshot or live).

=== {ec} Single Master -> Redis
[source,console]
----
riot replicate source:port target:port
----

=== Live {ec} Single Master -> Redis
[source,console]
----
riot replicate source:port target:port --mode live
----

[IMPORTANT]
====
In case {ec} is configured with https://docs.aws.amazon.com/Amazon{ec}/latest/red-ug/auth.html[AUTH TOKEN enabled], you need to pass `--source-tls` as well as `--source-pass` option:

[source,console,subs="+quotes"]
----
riot replicate source:port target:port --source-tls --source-pass <password>
----
====

=== {ec} Cluster -> Redis

[source,console]
----
riot replicate source:port target:port --source-cluster
----

NOTE: `--cluster` is an important parameter used ONLY for {ec} whenever cluster-mode is enabled.
Do note that the source database is specified first and the target database is specified after the replicate command and it is applicable for all the scenarios.

=== {ec} Single Master -> Redis (with specific database index)

[source,console]
----
riot replicate redis://source:port/db target:port
----

=== {ec} Single Master -> Redis with OSS Cluster
[source,console]
----
riot replicate source:port target:port --target-cluster
----

=== Live {ec} Cluster -> Redis with OSS Cluster

[source,console]
----
riot replicate source:port target:port --source-cluster --target-cluster --mode live
----

== Important Considerations

* It is recommended to test migration in UAT before production use.
* Once migration is completed, ensure that application traffic gets redirected to Redis endpoint successfully.
* It is recommended to perform the migration process during low traffic hours so as to avoid chances of data loss.


