[[_faq]]
= Frequently Asked Questions

Logs are cut off or missing::
This could be due to concurrency issues in the terminal when refreshing the progress bar and displaying logs.
Try running with job option `--progress log`.

Unknown options: '--keyspace', '--key'::
You must specify one or more Redis commands with import commands (<<_file_import,`file-import`>>, <<_faker,`faker`>>, <<_db_import,`db-import`>>).

ERR DUMP payload version or checksum are wrong::
Redis 7 DUMP format is not backwards compatible with previous versions.
To replicate between different Redis versions, use <<_replicate_struct,Type-Based Replication>>.

Process gets stuck during replication and eventually times out::
This could be due to big keys clogging the replication pipes.
In these cases it might be hard to catch the offending key(s).
Try running the same command with `--info` and `--progress log` so that all errors are reported.
Check the database with `redis-cli` {link_redis_bigkeys} and/or use reader options to filter these keys out.

NOAUTH Authentication required::
This issue occurs when you fail to supply the `--pass <password>` parameter.
