[[_files]]
= Files

{project-title} can import from and export to files in various formats:

* Delimited (CSV, TSV, PSV)
* Fixed-length (also known as fixed-width)
* JSON
* XML

[[_file_import]]
== File Import

The `file-import` command reads data from files and writes it to Redis.

The basic usage for file imports is:
[source]
----
riot -h <host> -p <port> file-import FILE... [REDIS COMMAND...]
----

To show the full usage, run:

[source]
----
riot file-import --help
----

You must specify at least one Redis command as a target.

[IMPORTANT]
====
Redis connection options apply to the root command (`riot`) and not to subcommands.

In this example the Redis options will not be taken into account:

[source,subs="verbatim,attributes"] 
----
riot file-import my.json hset -h myredis.com -p 6380
----
====

The keys that will be written are constructed from input records by concatenating the keyspace prefix and key fields.

image::mapping.svg[]

.Import into hashes with keyspace `blah:<id>`
[source]
----
riot file-import my.json hset --keyspace blah --keys id
----

.Import into JSON
[source]
----
include::{testdir}/file-import-json-elastic-jsonset[]
----

.Import into hashes *and* set TTL on the key
[source]
----
riot file-import my.json hset --keyspace blah --keys id expire --keyspace blah --keys id
----

.Import into hashes in keyspace `blah:<id>` *and* set TTL *and* add each `id` to a set named `myset`
[source]
----
riot file-import my.json hset --keyspace blah --keys id expire --keyspace blah --keys id sadd --keyspace myset --members id
----

[[_file_import_paths]]
=== Paths
Paths can include https://man7.org/linux/man-pages/man7/glob.7.html[wildcard patterns].

{project-title} will try to determine the file type from its extension (e.g. `.csv` or `.json`), but you can specify it with the `--filetype` option.

Gzipped files are supported and the extension before `.gz` is used (e.g. `myfile.json.gz` -> JSON type).

.Examples
* `/path/file.csv`
* `/path/file-*.csv`
* `/path/file.json`
* `\http://data.com/file.csv`
* `\http://data.com/file.json.gz`

TIP: Use `-` to read from standard input.

For AWS S3 buckets you can specify access and secret keys as well as the region for the bucket.

[source]
----
riot file-import s3://my-bucket/path/file.json --s3-region us-west-1 --s3-access xxxxxx --s3-secret xxxxxx
----

For Google Cloud Storage you can specify credentials and project id for the bucket:

[source]
----
riot file-import gs://my-bucket/path/file.json --gcs-key-file key.json --gcs-project-id my-gcp-project
----

[[_file_import_delimited]]
=== Delimited

The default delimiter character is comma (`,`).
It can be changed with the `--delimiter` option.

If the file has a header, use the `--header` option to automatically extract field names.
Otherwise specify the field names using the `--fields` option.

Let's consider this CSV file:

.https://storage.googleapis.com/jrx/beers.csv[beers.csv]
[format="csv", options="header",grid="none",frame="none",cols="5%,5%,5%,5%,35%,35%,8%,7%"]
|===
,abv,ibu,id,name,style,brewery_id,ounces
0,0.05,,1436,Pub Beer,American Pale Lager,408,12.0
1,0.066,,2265,Devil's Cup,American Pale Ale (APA),177,12.0
2,0.071,,2264,Rise of the Phoenix,American IPA,177,12.0
|===

The following command imports that CSV file into Redis as hashes using `beer` as the key prefix and `id` as primary key.
This creates hashes with keys `beer:1436`, `beer:2265`, ...

[source]
----
include::{testdir}/file-import-csv[]
----

This command imports a CSV file into a geo set named `airportgeo` with airport IDs as members:
[source]
----
include::{testdir}/file-import-geoadd[]
----

[[_file_import_fixed_length]]
=== Fixed-Length

Fixed-length files can be imported by specifying the width of each field using the `--ranges` option.

[source]
----
include::{testdir}/file-import-fw[]
----

[[_file_import_json]]
=== JSON

The expected format for JSON files is:

[source,json]
----
[
  {
    "...": "..."
  },
  {
    "...": "..."
  }
]
----

.JSON import example
[source]
----
include::{testdir}/file-import-json[]
----

JSON records are trees with potentially nested values that need to be flattened when the target is a Redis hash for example.

To that end, {project-title} uses a field naming convention to flatten JSON objects and arrays:

.Nested object
[cols="45%m,10%,45%m",frame="none",grid="none"]
|=========================================================

|`{ "field": { "sub": "value" } }`| -> | `field.sub=value`

|=========================================================

.Array
[cols="45%m,10%,45%m",frame="none",grid="none"]
|=========================================================

|`{ "field": [1, 2, 3] }`| -> | `field[0]=1 field[1]=2 field[2]=3`

|=========================================================

[[_file_import_xml]]
=== XML

Here is a sample XML file that can be imported by {project-title}:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<records>
    <trade>
        <isin>XYZ0001</isin>
        <quantity>5</quantity>
        <price>11.39</price>
        <customer>Customer1</customer>
    </trade>
    <trade>
        <isin>XYZ0002</isin>
        <quantity>2</quantity>
        <price>72.99</price>
        <customer>Customer2c</customer>
    </trade>
    <trade>
        <isin>XYZ0003</isin>
        <quantity>9</quantity>
        <price>99.99</price>
        <customer>Customer3</customer>
    </trade>
</records>
----

.XML Import Example
[source]
----
include::{testdir}/file-import-xml[]
----

=== Regular Expressions

In addition to general <<_processing,processing>> you can perform field extraction using regular expressions.

.Regex example
[source]
----
riot file-import --regex name="(?<first>\w+)\/(?<last>\w+)" ...
----



[[_file_export]]
== File Export

The `file-export` command reads data from a Redis database and writes it to a JSON or XML file, potentially gzip-compressed.

The general usage is:
[source]
----
riot -h <host> -p <port> file-export FILE
----

To show the full usage, run:
[source]
----
riot file-export --help
----

.Export to JSON
[source]
----
include::{testdir}/file-export-json[]
----

.Sample JSON-export file
[source,json]
----
include::{includedir}/../resources/redis-dump.json[]
----

.Export to compressed JSON
[source]
----
include::{testdir}/file-export-json-gz[]
----

.Export to XML
[source]
----
include::{testdir}/file-export-xml[]
----



[[_dump_import]]
== Dump Import

{project-title} can import Redis data structure files in JSON or XML formats. See <<_file_export, File Export>> section to generate such files.

.Example
[source]
----
include::{testdir}/dump-import[]
----