[[_file]]
= Files

{project-title} includes two commands to work with files in various formats:

* <<_file_import,`file-import`>>: Import data from files
* <<_file_export,`file-export`>>: Export Redis data structures to files

[[_file_import]]
== File Import

The `file-import` command reads data from files and writes it to Redis.

The basic usage for file imports is:

[source,console]
----
riot file-import [OPTIONS] FILE... [REDIS COMMAND...]
----

To show the full usage, run:

[source,console]
----
riot file-import --help
----

File paths can include https://man7.org/linux/man-pages/man7/glob.7.html[wildcard patterns].

{project-title} will try to determine the file type from its extension (e.g. `.csv` or `.json`), but you can specify it with the `--filetype` option.

Gzipped files are supported and the extension before `.gz` is used (e.g. `myfile.json.gz` -> `json`).

.Examples
* `/path/file.csv`
* `/path/file-*.csv`
* `/path/file.json`
* `\http://data.com/file.csv`
* `\http://data.com/file.json.gz`

TIP: Use `-` to read from standard input.

Amazon S3 and Google Cloud Storage buckets are supported.

.Importing from Amazon S3
[source,console]
----
include::{testdir}/file-import-s3[]
----

.Importing from Google Cloud Storage
[source,console]
----
include::{testdir}/file-import-gcs[]
----


[[_file_import_struct]]
=== Data Structures

If no `REDIS COMMAND` is specified, it is assumed that the input file(s) contain Redis data structures serialized as JSON or XML. See the <<_file_export, File Export>> section to learn about the expected format and how to generate such files.

.Example
[source,console]
----
include::{testdir}/file-import-json[]
----

[[_file_import_commands]]
=== Redis Commands

When one or more `REDIS COMMAND`s are specified, these commands are called for each input record.

[IMPORTANT]
====
Redis client options apply to the root command (`riot`) and not to Redis commands.

In this example Redis client options will not be taken into account:

[source,subs="verbatim,attributes"] 
----
riot file-import my.json hset -h myredis.com -p 6380
----
====

Redis command keys are constructed from input records by concatenating keyspace prefix and key fields.

image::mapping.svg[]

.Import into hashes with keyspace `blah:<id>`
[source,console]
----
riot file-import my.json hset --keyspace blah --key id
----

.Import into JSON
[source,console]
----
include::{testdir}/file-import-json-elastic-jsonset[]
----

.Import into hashes *and* set TTL on the key
[source,console]
----
riot file-import my.json hset --keyspace blah --key id expire --keyspace blah --key id
----

.Import into hashes in keyspace `blah:<id>` *and* set TTL *and* add each `id` to a set named `myset`
[source,console]
----
riot file-import my.json hset --keyspace blah --key id expire --keyspace blah --key id sadd --keyspace myset --member id
----

[[_file_import_delimited]]
=== Delimited (CSV)

The default delimiter character is comma (`,`).
It can be changed with the `--delimiter` option.

If the file has a header, use the `--header` option to automatically extract field names.
Otherwise specify the field names using the `--fields` option.

Let's consider this CSV file:

.beers.csv
[format="csv",options="header",cols="5,5,5,5,20,20,8,8"]
|===
row,abv,ibu,id,name,style,brewery,ounces
1,0.079,45,321,Fireside Chat (2010),Winter Warmer,368,12.0
2,0.068,65,173,Back in Black,American Black Ale,368,12.0
3,0.083,35,11,Monk's Blood,Belgian Dark Ale,368,12.0
|===

The following command imports this CSV into Redis as hashes using `beer` as the key prefix and `id` as primary key.
[source,console]
----
include::{testdir}/file-import-csv[]
----

This creates hashes with keys `beer:321`, `beer:173`, ...

This command imports a CSV file into a geo set named `airportgeo` with airport IDs as members:
[source,console]
----
include::{testdir}/file-import-geoadd[]
----

[[_file_import_fixed_length]]
=== Fixed-Length (Fixed-Width)

Fixed-length files can be imported by specifying the width of each field using the `--ranges` option.

[source,console]
----
include::{testdir}/file-import-fw[]
----

[[_file_import_json]]
=== JSON

The expected format for JSON files is:

[source,json]
----
[
  {
    "...": "..."
  },
  {
    "...": "..."
  }
]
----

.JSON import example
[source,console]
----
include::{testdir}/file-import-json[]
----

JSON records are trees with potentially nested values that need to be flattened when the target is a Redis hash for example.

To that end, {project-title} uses a field naming convention to flatten JSON objects and arrays:

.Nested object
[cols="45%m,10%,45%m",frame="none",grid="none"]
|=========================================================

|`{ "field": { "sub": "value" } }`| -> | `field.sub=value`

|=========================================================

.Array
[cols="45%m,10%,45%m",frame="none",grid="none"]
|=========================================================

|`{ "field": [1, 2, 3] }`| -> | `field[0]=1 field[1]=2 field[2]=3`

|=========================================================

[[_file_import_xml]]
=== XML

Here is a sample XML file that can be imported by {project-title}:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<records>
    <trade>
        <isin>XYZ0001</isin>
        <quantity>5</quantity>
        <price>11.39</price>
        <customer>Customer1</customer>
    </trade>
    <trade>
        <isin>XYZ0002</isin>
        <quantity>2</quantity>
        <price>72.99</price>
        <customer>Customer2c</customer>
    </trade>
    <trade>
        <isin>XYZ0003</isin>
        <quantity>9</quantity>
        <price>99.99</price>
        <customer>Customer3</customer>
    </trade>
</records>
----

.XML Import Example
[source,console]
----
include::{testdir}/file-import-xml[]
----


[[_file_export]]
== File Export

The `file-export` command reads data from a Redis database and writes it to a JSON or XML file, potentially gzip-compressed.

The general usage is:
[source,console]
----
riot file-export [OPTIONS] FILE
----

To show the full usage, run:
[source,console]
----
riot file-export --help
----

[[_file_export_json]]
=== JSON

.Export to JSON
[source,console]
----
include::{testdir}/file-export-json[]
----

.Sample JSON-export file
[source,json]
----
include::{includedir}/../resources/redis-dump.json[]
----

.Export to compressed JSON
[source,console]
----
include::{testdir}/file-export-json-gz[]
----

[[_file_export_xml]]
=== XML
.Export to XML
[source,console]
----
include::{testdir}/file-export-xml[]
----


