[[_generators]]
= Generators

{project-title} includes two data generators that can be used to quickly mock up a dataset in Redis.

[[_faker]]
== Faker

The `faker-import` command generates data using {link_datafaker}.

[source,console]
----
riot faker-import [OPTIONS] SPEL... [REDIS COMMAND...]
----

where SPEL is a {link_spel} field in the form `field="expression"`.

To show the full usage, run:

[source,console]
----
riot faker-import --help
----

You must specify at least one Redis command as a target.

[IMPORTANT]
====
Redis connection options apply to the root command (`riot`) and not to subcommands.

In this example the Redis options will not be taken into account:

[source,subs="verbatim,attributes"]
----
riot faker-import id="index" hset -h myredis.com -p 6380
----
====

[[_faker_keys]]
=== Keys

Keys are constructed from input records by concatenating the keyspace prefix and key fields.

image::mapping.svg[]

.HSET example
[source,console]
----
include::{testdir}/faker-import-hset[]
----

.SADD example
[source,console]
----
include::{testdir}/faker-import-sadd[]
----

[[_faker_providers]]
=== Data Providers

Faker offers many data providers.
Most providers don't take any arguments and can be called directly:

.Simple Faker example
[source,console]
----
riot faker-import firstName="name.firstName"
----

Some providers take parameters:

.Parameter Faker example
[source,console]
----
riot faker-import lease="number.digits(2)"
----

Refer to {link_datafaker_doc} for complete documentation.

[[_faker_builtin_fields]]
=== Built-in Fields

In addition to the Faker fields specified with `field="expression"` you can use these built-in fields:

`index`:: current iteration number.

`thread`:: current thread id.
Useful for multithreaded data generation.

.Multithreaded data generator
[source,console]
----
include::{testdir}/faker-import-threads[]
----

[[_faker_redisearch]]
=== RediSearch

You can infer Faker fields from a RediSearch index using the `--infer` option:

[source,console]
----
include::{testdir}/faker-import-infer[]
----

[[_generate]]
== Data Structures

The `generate` command generates data-structures for Redis, RedisJSON and RedisTimeSeries.

[source,console]
----
riot generate [OPTIONS]
----

