[[_processing]]
= Processing

{project-title} lets you process incoming records in different ways:

* SpEL processors (`--proc`)
* Regex field extraction (`--regex`)
* SpEL filtering (`--filter`)

[[_spel_proc]]
== SpEL Processors

These processors allow you to create/update/delete fields using the {link_spel} (SpEL):

* `field1='foo'` -> generate a field named `field1` containing the string `foo`
* `temp=(temp-32)*5/9` -> convert from Fahrenheit to Celsius
* `name=remove(first).concat(remove(last))` -> concatenate `first` and `last` fields and delete them
* `field2=null` -> delete `field2`

Input fields are accessed by name (e.g. `field3=field1+field2`).

Processors have access to the SpEL evaluation context and also this function:

* `geo`: Convenience method that takes a longitude and a latitude to produce a RediSearch geo-location string in the form `longitude,latitude` (e.g. `location=#geo(lon,lat)`)

.Processor example
[source]
----
riot file-import --proc epoch="#date.parse(mydate).getTime()" location="#geo(lon,lat)" name="#redis.hget('person1','lastName')" ...
----

[[_architecture_regex]]
=== Regular Expressions

Extract patterns from source fields using regular expressions:
[source]
----
riot file-import --regex name="(?<first>\w+)\/(?<last>\w+)" ...
----

[[_architecture_filters]]
=== Filters

Filters allow you to exclude records that don't match a SpEL boolean expression.

For example this filter will only keep records where the `value` field is a series of digits:

[source]
----
riot file-import --filter "value matches '\\d+'" ...
----