= Processing

The following processors can be applied to records in that order:

* Transforms
* Regular expressions
* Filters

== Transforms

Transforms allow you to create/update/delete fields using the https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions[Spring Expression Language] (SpEL):

* `field1='foo'` -> generate a field named `field1` containing the string `foo`
* `temp=(temp-32)*5/9` -> convert temperature from Fahrenheit to Celsius
* `name=remove(first).concat(remove(last))` -> concatenate `first` and `last` fields and delete them
* `field2=null` -> delete `field2`

Input fields are accessed by name (e.g. `field3=field1+field2`).

The transform processor also exposes functions and variables that can be accessed using the `#` prefix:

`date`;; Date parser/formatter (https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html[API doc])
`geo`;; Convenience method that takes a longitude and a latitude to produce a RediSearch geo-location string in the form: `longitude,latitude`
`index`;; Sequence number of the item being generated
`redis`;; Handle to invoke Redis commands (https://lettuce.io/core/release/api/io/lettuce/core/api/sync/RedisCommands.html[API doc])

.Processor Example
[subs="attributes,+quotes"]
....
[green]#{connector}# import --process epoch=[olive]#"#date.parse(mydate).getTime()"# location=[olive]#"#geo(lon,lat)"# id=[olive]#"#index"# name=[olive]#"#redis.hget('person1','lastName')"# ...
....

== Regular Expressions

Extract patterns from source fields using regular expressions:
[subs="attributes,+quotes"]
....
[green]#{connector}# import --regex name=[olive]#"(?<first>\w+)\/(?<last>\w+)"# ...
....

== Filters

Keep records that match a SpEL boolean expression.

For example this filter will only keep records where the `value` field is a series of digits:

[subs="attributes,+quotes"]
....
[green]#{connector}# import --filter "value matches '\\d+'" ...
....

