[[_quickstart]]
= Quick Start

This section helps you get started with {project-title}.

[[_install]]
== Install

{project-title} can be installed on Linux, macOS, and Windows platforms and can be used as a standalone tool that connects remotely to a Redis database.
It is not required to run locally on a Redis server.


[[_homebrew_install]]
.Homebrew (macOS & Linux)
[source]
----
brew install redis-developer/tap/riot
----

[[_scoop_install]]
.Scoop (Windows)
[source]
----
scoop bucket add redis-developer https://github.com/redis-developer/scoop.git
scoop install riot
----

[[_manual_install]]
.Manual installation (all platforms)
Download the pre-compiled binary from the link:{project-url}/releases[releases page], uncompress and copy to the desired location.

[NOTE]
====
`riot-{project-version}.zip` requires Java 11 or greater to be installed.
`riot-standalone-{project-version}-*.zip` includes its own Java runtime and does not require a Java installation.
====

[[_docker_install]]
.Docker
[source]
----
docker run fieldengineering/riot [OPTIONS] [COMMAND]
----

[[_usage]]
== Usage

You can launch {project-title} with the following command:

[source]
----
riot
----

This will show usage help, which you can also get by running:

[source]
----
riot --help
----

[TIP]
====
`--help` is available on any command and subcommand:

[source]
----
riot command --help
riot command subcommand --help
----
====

[[_shell_completion]]
=== Shell Completion
Run the following command to give `riot` TAB completion in the current shell:

[source]
----
$ source <(riot generate-completion)
----

[[_manpage]]
=== Manual
The manual is available link:manpage/riot.html[here]

