[[_replication]]
= Replication

Most Redis migration tools available today are offline in nature.
Migrating data from AWS ElastiCache to Redis Enterprise Cloud for example means backing up your Elasticache data to an AWS S3 bucket and importing it into Redis Enterprise Cloud using its UI.

Redis has a replication command called https://redis.io/commands/replicaof[REPLICAOF] but it is not always available (see https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/RestrictedCommands.html[ElastiCache restrictions]).
Instead, {project-title} implements <<_architecture,client-side replication>> using *dump & restore* or *type-based read & write*. Both snapshot and live replication modes are supported.

WARNING: Please note that {project-title} is NEITHER recommended NOR officially supported by Redis, Inc.

[[_replication_usage]]
== Usage

[source]
----
riot <source> replicate <target> --mode <snapshot|live|compare> [--type] [OPTIONS]
----

For the full usage, run:
[source]
----
riot replicate --help
----

[[_replication_mode]]
== Replication Mode

=== Snapshot

This mode iterates over the keys in the source Redis database using scan.

=== Live
This mode builds upon snapshot replication by listening for changes on the source Redis database.
Whenever a key is modified its corresponding value is read and propagated to the target Redis database.

Live replication relies on keyspace notifications for capturing these changes.

**Make sure the source database has keyspace notifications enabled** using:

* `redis.conf`: `notify-keyspace-events = KA`
* `CONFIG SET notify-keyspace-events KA`

For more details see {link_redis_notif}.

[WARNING]
====
The live replication mechanism does not guarantee data consistency.
Redis sends keyspace notifications over pub/sub which does not provide guaranteed delivery.
It is possible that {project-title} can miss some notifications in case of network failures for example.

Also, depending on the type, size, and rate of change of data structures on the source it is possible that {project-title} cannot keep up with the change stream.
For example if a big set is repeatedly updated, {project-title} will need to read the whole set on each update and transfer it over to the target database.
With a big-enough set, {project-title} could fall behind and the internal queue could fill up leading up to updates being dropped.

For those potentially problematic migrations it is recommend to perform some preliminary sizing using Redis statistics and `bigkeys`/`memkeys` in tandem with `--mem-limit`.
If you need assistance please contact your Redis account team.
====

[[_replication_type]]
== Replication Type

[[_replication_dump_restore]]
=== Dump & Restore

The default replication mechanism is Dump & Restore:

1. Scan for keys in the source Redis database.
If live replication is enabled the reader also subscribes to keyspace notifications to generate a continuous stream of keys.

2. Reader threads iterate over the keys to read corresponding values (DUMP) and TTLs.

3. Reader threads enqueue key/value/TTL tuples into the reader queue, from which the writer dequeues key/value/TTL tuples and writes them to the target Redis database by calling RESTORE and EXPIRE.

[[_replication_type_based]]
=== Type-Based Replication

There are situations where Dump & Restore cannot be used, for example:

* The target Redis database does not support the RESTORE command ({link_redis_crdb})
* Incompatible DUMP formats between source and target ({link_redis_7})

In those cases you can use another replication strategy called *Type-Based Replication* where each key is introspected to determine the type of data structure and which read/write commands to use:

[%header,cols="h,1,1"]
|=========================================================
|Type|Read|Write

|Hash|`HGETALL`|`HSET`
|JSON|`JSON.GET`|`JSON.SET`
|List|`LRANGE`|`RPUSH`
|Set|`SMEMBERS`|`SADD`
|Sorted Set|`ZRANGE`|`ZADD`
|Stream|`XRANGE`|`XADD`
|String|`GET`|`SET`
|TimeSeries|`TS.RANGE`|`TS.ADD`

|=========================================================

WARNING: This replication strategy is more intensive in terms of CPU, memory, and network for the machines running {project-title} as well as the source and target Redis databases.
Adjust number of threads, batch and queue sizes accordingly.

.Snapshot replication example
[source]
----
include::{testdir}/replicate[]
----

.Live replication example
[source]
----
include::{testdir}/replicate-live[]
----

.Type-based replication example
[source]
----
include::{testdir}/replicate-struct[]
----

.Live type-based replication example
[source]
----
include::{testdir}/replicate-live-struct[]
----

[[_replication_progress]]
== Progress Reporting
Each process (scan iterator and/or event listener in case of live replication) has a corresponding status bar that shows the process name and its progress:

Scanning::
    Percentage of keys that have been replicated => replicated / total.
    The total number of keys is calculated when the process starts and it can change by the time it is finished (for example if keys are deleted or added during the replication).
    The progress bar is only a rough indicator.
Listening::
    Progress is indefinite as total number of keys is unknown.


[[_replication_compare]]
== Compare

Once replication is complete, {project-title} performs a verification step by iterating over keys in the source database and comparing values and TTLs between source and target databases.

The verification step happens automatically after the scan is complete (snapshot replication), or for live replication when keyspace notifications have become idle (see <<_replication_usage, Usage>> section).

Verification can also be run on-demand using the `compare` mode:
[source]
----
riot <source> replicate --mode compare <target>
----

The output looks like this:

----
missing: 123, type: 54, value: 7, TTL: 19
----

missing::
Number of keys only present in source database

type::
Number of keys with mismatched data structure type

value::
Number of keys with mismatched value

TTL::
Number of keys with mismatched TTL i.e. difference is greater than tolerance (can be specified with `--ttl-tolerance`)

There are 2 comparison modes available through `--compare-mode`:

* Quick (default): compares key types
* Full: compares key types, values, and TTLs

To show which keys are different use the `--show-diffs` option:

[source]
----
riot <source> replicate <target> --show-diffs
----

[[_replication_performance_tuning]]
== Performance Tuning

Performance tuning is an art but {project-title} offers some options to identify potential bottlenecks.
In addition to <<_batching,batch>> and <<_threads,threads>> options you have the `--dry-run` option which disables writing to the target Redis database so that you can tune the reader in isolation.
Add that option to your existing `replicate` command-line to compare replication speeds with and without writing to the target Redis database:

[source]
----
riot <source> replicate <target> --dry-run
----


