[[_replicate]]
= Replicate

Most Redis migration tools available today are offline in nature.
Migrating data from AWS ElastiCache to Redis Enterprise Cloud for example means backing up your Elasticache data to an AWS S3 bucket and importing it into Redis Enterprise Cloud using its UI.

Redis has a replication command called https://redis.io/commands/replicaof[REPLICAOF] but it is not always available (see https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/RestrictedCommands.html[ElastiCache restrictions]).
Instead, {project-title} implements <<_architecture,client-side replication>> using *dump & restore* or *type-based read & write*. Both snapshot and live replication modes are supported.

WARNING: Please note that {project-title} is NEITHER recommended NOR officially supported by Redis, Inc.

image::replication-architecture.svg[]

The basic replication mechanism is as follows:

1. Identify source keys to be replicated using scan and/or keyspace notifications depending on the <<_replicate_mode,replication mode>>.

2. Read data associated with each key using <<_replicate_dump,dump>> or <<_replicate_struct,type-specific commands>>.

3. Write each key to the target using <<_replicate_dump,restore>> or <<_replicate_struct,type-specific commands>>.

[source,console]
----
riot replicate SOURCE TARGET [--mode <scan|live|liveonly>] [--struct] [OPTIONS]
----

For the full usage, run:
[source,console]
----
riot replicate --help
----

A status bar shows progress with a percentage of keys that have been replicated.
The total number of keys is estimated when the process starts and it can change by the time it is finished, for example if keys are deleted or added during replication.

[[_replicate_mode]]
[discrete]
== Mode

[discrete]
=== Scan
This mode uses the `SCAN` command to identify keys to propagate to the target Redis database.

[discrete]
=== Live
This mode builds upon scan replication by also listening for changes on the source Redis database.
Whenever a key is modified its corresponding value is read and propagated to the target Redis database.

Live replication relies on keyspace notifications for capturing these changes.

**Make sure the source database has keyspace notifications enabled** using:

* `redis.conf`: `notify-keyspace-events = KEA`
* `CONFIG SET notify-keyspace-events KEA`

For more details see {link_redis_notif}.

[WARNING]
====
The live replication mechanism does not guarantee data consistency.
Redis sends keyspace notifications over pub/sub which does not provide guaranteed delivery.
It is possible that {project-title} can miss some notifications in case of network failures for example.

Also, depending on the type, size, and rate of change of data structures on the source it is possible that {project-title} cannot keep up with the change stream.
For example if a big set is repeatedly updated, {project-title} will need to read the whole set on each update and transfer it over to the target database.
With a big-enough set, {project-title} could fall behind and the internal queue could fill up leading up to updates being dropped.

For those potentially problematic migrations it is recommend to perform some preliminary sizing using Redis statistics and `bigkeys`/`memkeys` in tandem with `--mem-limit`.
If you need assistance please contact your Redis account team.
====

[discrete]
=== Live Only
In this mode only keyspace notifications are used.

[[_replicate_dump]]
[discrete]
== Dump & Restore

The default replication mechanism is Dump & Restore:

1. Scan for keys in the source Redis database.
If live replication is enabled the reader also subscribes to keyspace notifications to generate a continuous stream of keys.

2. Reader threads iterate over the keys to read corresponding values (DUMP) and TTLs.

3. Reader threads enqueue key/value/TTL tuples into the reader queue, from which the writer dequeues key/value/TTL tuples and writes them to the target Redis database by calling RESTORE and EXPIRE.

[[_replicate_struct]]
[discrete]
== Data Structure

There are situations where Dump & Restore cannot be used, for example:

* The target Redis database does not support the RESTORE command ({link_redis_crdb})
* Incompatible DUMP formats between source and target ({link_redis_7})

In those cases you can use another replication strategy that is data structure-specific: each key is introspected to determine its type and then use the corresponding read/write commands:

[%header,cols="h,1,1"]
|=========================================================
|Type|Read|Write

|Hash|`HGETALL`|`HSET`
|JSON|`JSON.GET`|`JSON.SET`
|List|`LRANGE`|`RPUSH`
|Set|`SMEMBERS`|`SADD`
|Sorted Set|`ZRANGE`|`ZADD`
|Stream|`XRANGE`|`XADD`
|String|`GET`|`SET`
|TimeSeries|`TS.RANGE`|`TS.ADD`

|=========================================================

WARNING: This replication strategy is more intensive in terms of CPU, memory, and network for all the machines involved (source Redis, target Redis, and {project-title} machines).
Adjust number of threads, batch and queue sizes accordingly.

.Snapshot replication example
[source,console]
----
include::{testdir}/replicate[]
----

.Live replication example
[source,console]
----
include::{testdir}/replicate-live[]
----

.Type-based replication example
[source,console]
----
include::{testdir}/replicate-struct[]
----

.Live type-based replication example
[source,console]
----
include::{testdir}/replicate-live-struct[]
----

[[_replicate_compare]]
[discrete]
== Compare

Once replication is complete, {project-title} performs a verification step by reading keys in the source database and comparing them against the target database.

The verification step happens automatically after the scan is complete (snapshot replication), or for live replication when keyspace notifications have become idle.

Verification can also be run on-demand using the <<_compare,`compare`> command.

[[_replicate_performance]]
[discrete]
== Performance

Performance tuning is an art but {project-title} offers some options to identify potential bottlenecks.
In addition to <<_batching,batch>> and <<_threads,threads>> options you have the `--dry-run` option which disables writing to the target Redis database so that you can tune the reader in isolation.
Add that option to your existing `replicate` command-line to compare replication speeds with and without writing to the target Redis database.


