[[_replication]]
= Replication

The `replicate` command reads data from a *source* Redis database and writes to a *target* Redis database.

image::replication-architecture.svg[]

The replication mechanism is as follows:

1. Identify source keys to be replicated using scan and/or keyspace notifications depending on the <<_replication_mode,replication mode>>.

2. Read data associated with each key using <<_replication_type_dump,dump>> or <<_replication_type_struct,type-specific commands>>.

3. Write each key to the target using <<_replication_type_dump,restore>> or <<_replication_type_struct,type-specific commands>>.

The basic usage is:

[source,console]
----
riot replicate [OPTIONS] SOURCE TARGET
----

where SOURCE and TARGET are <<_redis_uri,Redis URIs>>.

For the full usage, run:
[source,console]
----
riot replicate --help
----

TIP: To replicate a Redis logical database other than the default (`0`), specify the database in the source Redis URI.
For example `riot replicate redis://source:6379/1 redis://target:6379` replicates database `1`.

[[_replication_mode]]
== Replication Mode

Replication starts with identifying keys to be replicated from the source Redis database.
The `--mode` option allows you to specify how {project-title} identifies keys to be replicated:

* iterate over keys with a key scan (`--mode scan`)
* received by a keyspace notification subscriber (`--mode liveonly`)
* or both (`--mode live`)

[[_replication_mode_scan]]
=== Scan 

This key reader scans for keys using the Redis https://redis.io/docs/latest/commands/scan/[`SCAN` command]:

```
SCAN cursor [MATCH pattern] [COUNT count] [TYPE type]
```

`MATCH pattern`:: configured with the `--key-pattern` option
`TYPE type`:: configured with the `--key-type` option
`COUNT count`:: configured with the `--scan-count` option

INFO: In cluster mode keys are scanned in parallel across cluster nodes.

The status bar shows progress with a percentage of keys that have been replicated.
The total number of keys is estimated when the replication process starts and it can change by the time it is finished, for example if keys are deleted or added during replication.

.Scan replication example
[source,console]
----
include::{testdir}/replicate[]
----

[[_replication_mode_live]]
=== Live

The key notification reader listens for key changes using keyspace notifications.

**Make sure the source database has keyspace notifications enabled** using:

* `redis.conf`: `notify-keyspace-events = KEA`
* `CONFIG SET notify-keyspace-events KEA`

For more details see {link_redis_notif}.

.Live replication example
[source,console]
----
include::{testdir}/replicate-live[]
----

[WARNING]
====
The live replication mechanism does not guarantee data consistency.
Redis sends keyspace notifications over pub/sub which does not provide guaranteed delivery.
It is possible that {project-title} can miss some notifications in case of network failures for example.

Also, depending on the type, size, and rate of change of data structures on the source it is possible that {project-title} cannot keep up with the change stream.
For example if a big set is repeatedly updated, {project-title} will need to read the whole set on each update and transfer it over to the target database.
With a big-enough set, {project-title} could fall behind and the internal queue could fill up leading up to updates being dropped.

For those potentially problematic migrations it is recommend to perform some preliminary sizing using Redis statistics and `bigkeys`/`memkeys` in tandem with `--mem-limit`.
If you need assistance please contact your Redis account team.
====

== Replication Types

{project-title} offers two different mechanisms for reading and writing keys:

* Dump & restore (default)
* Data structure replication (`--struct`)

[[_replication_type_dump]]
=== Dump & Restore

The default replication mechanism is Dump & Restore:

1. Scan for keys in the source Redis database.
If live replication is enabled the reader also subscribes to keyspace notifications to generate a continuous stream of keys.

2. Reader threads iterate over the keys to read corresponding values (DUMP) and TTLs.

3. Reader threads enqueue key/value/TTL tuples into the reader queue, from which the writer dequeues key/value/TTL tuples and writes them to the target Redis database by calling RESTORE and EXPIRE.

[[_replication_type_struct]]
=== Data Structure Replication

There are situations where Dump & Restore cannot be used, for example:

* The target Redis database does not support the RESTORE command ({link_redis_crdb})
* Incompatible DUMP formats between source and target ({link_redis_7})

In those cases you can use another replication strategy that is data structure-specific: each key is introspected to determine its type and then use the corresponding read/write commands.

[%header,cols="h,1,1"]
|=========================================================
|Type|Read|Write

|Hash|`HGETALL`|`HSET`
|JSON|`JSON.GET`|`JSON.SET`
|List|`LRANGE`|`RPUSH`
|Set|`SMEMBERS`|`SADD`
|Sorted Set|`ZRANGE`|`ZADD`
|Stream|`XRANGE`|`XADD`
|String|`GET`|`SET`
|TimeSeries|`TS.RANGE`|`TS.ADD`

|=========================================================

WARNING: This replication strategy is more intensive in terms of CPU, memory, and network for all the machines involved (source Redis, target Redis, and {project-title} machines).
Adjust number of threads, batch and queue sizes accordingly.


.Type-based replication example
[source,console]
----
include::{testdir}/replicate-struct[]
----

.Live type-based replication example
[source,console]
----
include::{testdir}/replicate-live-struct[]
----

[[_replication_compare]]
== Compare

Once replication is complete, {project-title} performs a verification step by reading keys in the source database and comparing them against the target database.

The verification step happens automatically after the scan is complete (snapshot replication), or for live replication when keyspace notifications have become idle.

Verification can also be run on-demand using the `compare` command:

[source,console]
----
riot compare SOURCE TARGET [OPTIONS]
----

The output looks like this:

----
Verification failed (type: 225,062, missing: 485,450)
----

missing::
Number of keys in source but not in target.

type::
Number of keys with mismatched types (e.g. hash vs string).

value::
Number of keys with mismatched values.

ttl::
Number of keys with mismatched TTL i.e. difference is greater than tolerance (can be specified with `--ttl-tolerance`).

There are 2 comparison modes available through `--compare` (`--quick` for `compare` command):

Quick (default):: Compare key types and TTLs.
Full:: Compare key types, TTLs, and values.

To show which keys differ, use the `--show-diffs` option.


[[_replication_performance]]
== Performance

Performance tuning is an art but {project-title} offers some options to identify potential bottlenecks.
In addition to <<_batching,`--batch`>> and <<_multi_threading,`--threads`>> options you have the `--dry-run` option which disables writing to the target Redis database so that you can tune the reader in isolation.
Add that option to your existing `replicate` command-line to compare replication speeds with and without writing to the target Redis database.


