[[_replicate]]
= Replication

Most Redis migration tools available today are offline in nature.
Migrating data from AWS ElastiCache to Redis Enterprise Cloud for example means backing up your Elasticache data to an AWS S3 bucket and importing it into Redis Enterprise Cloud using its UI.

Redis has a replication command called https://redis.io/commands/replicaof[REPLICAOF] but it is not always available (see https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/RestrictedCommands.html[ElastiCache restrictions]).
Instead, {project-title} implements <<_architecture,client-side replication>> using *dump & restore* or *type-based read & write*. Both snapshot and live replication modes are supported.

WARNING: Please note that {project-title} is NEITHER recommended NOR officially supported by Redis, Inc.

[[_replicate_usage]]
== Usage

[source]
----
riot <source> replicate <target> --mode <snapshot|live|compare> [OPTIONS]
----

For the full usage, run:
[source]
----
riot replicate --help
----

.Snapshot replication example
[source]
----
include::{testdir}/replicate[]
----

.Live replication example
[source]
----
include::{testdir}/replicate-live[]
----

[[_target_redis_connection_options]]
=== Target connection options
Connection options for the target database are the same as the source Redis connection options:

include::{includedir}/redis-connection-options.adoc[leveloffset=+2]

[[_replicate_options]]
=== Replication Options

`--event-order`:: Keyspace notification ordering strategy.
  `fifo`::: Keeps order of notifications as they are received.
  `priority`::: Orders notifications based on the underlying data-structure: `string` > `hash` > `json` > `list` > `set` > `zset` > `stream` > `timeseries`.
`--event-queue`:: Capacity of the keyspace notification queue (default: `10000`).
`--flush-interval`::  Max duration between flushes (default: `50`).
`--idle-timeout`:: Min duration of inactivity to consider transfer complete (default: no timeout).
`--key-process`:: SpEL expression to transform each key.
`--mode`:: Replication mode: snapshot, live, or live only.
  `snapshot`::: Initial replication using key scan.
  `liveonly`::: Continuous replication using keyspace notifications (only keys that change are replicated).
  `live`::: Initial and continuous replication using key scan and keyspace notifications in parallel.
`--no-verify`:: Disable verifying target against source dataset after replication.
`--show-diffs`:: Print details of key mismatches during dataset verification.
`--target-pool`:: Max connections for target Redis pool (default: `8`).
`--target-read-from`:: Which target Redis cluster nodes to read data from.
`--ttl-tolerance`:: Max TTL difference to use for dataset verification (default: `100`).
`--type`:: Replication strategy: DUMP, DS (default: DUMP).

    
[[_replicate_type]]
=== Replication Type
`--type dump`:: <<_replicate_dump_and_restore,DUMP & RESTORE>>.
`--type ds`:: <<_replicate_type_based,Type-based>>

[[_source_redis_reader_options]]
=== Source reader options
include::{includedir}/redis-reader-options.adoc[leveloffset=+2]

[[_replicate_performance_tuning]]
=== Performance Tuning

Performance tuning is an art but {project-title} offers some options to identify potential bottlenecks.
In addition to the <<_architecture_batch,batch>> and <<_architecture_threads,threads>> options you have the `--dry-run` option which disables writing to the target Redis database so that you can tune the <<_source_redis_reader_options,reader>> in isolation.
Add that option to your existing `replicate` command-line to compare replication speeds with and without writing to the target Redis database:

[source]
----
riot <source> replicate <target> --dry-run
----

[[_replicate_verification]]
=== Verification

Once replication is complete {project-title} will perform a verification step by iterating over keys in the source database and comparing values and TTLs between source and target databases.

The verification step happens automatically after the scan is complete (snapshot replication), or for live replication when keyspace notifications have become idle (see <<_replicate_usage, Usage>> section).

Verification can also be run on-demand using the `compare` mode:
[source]
----
riot <source> replicate --mode compare <target>
----

The output looks like this:

----
123 missing, 54 type, 7 value, 19 ttl
----

missing:: number of keys only present in source database
type:: number of keys with mismatched data structure type
value:: number of keys with mismatched value
ttl:: number of keys with mismatched TTL i.e. difference is greater than tolerance (can be specified with `--ttl-tolerance`)

To show which keys are different use the `--show-diffs` option:

[source]
----
riot <source> replicate <target> --show-diffs
----

[[_replicate_progress]]
=== Progress

Each process (scan iterator and/or event listener in case of live replication) has a corresponding status bar that shows the process name and its progress:

Scanning::
    Percentage of keys that have been replicated => replicated / total.
    The total number of keys is calculated when the process starts and it can change by the time it is finished (for example if keys are deleted or added during the replication).
    The progress bar is only a rough indicator.
Listening::
    Progress is indefinite as total number of keys is unknown.

[[_replicate_architecture]]
== Architecture

[[_replicate_live]]
=== Live Replication

In live replication mode {project-title} listens for changes happening on the source database using keyspace notifications.
Each time a key is modified, {project-title} reads the corresponding value and propagates that change to the target database.

Live replication relies on keyspace notifications. 
**Make sure the source database has keyspace notifications enabled** using `notify-keyspace-events = KA` in `redis.conf` or via `CONFIG SET`.
For more details see {link_redis_notif}.

[WARNING]
====
The live replication mechanism does not guarantee data consistency.
Redis sends keyspace notifications over pub/sub which does not provide guaranteed delivery.
It is possible that {project-title} can miss some notifications in case of network failures for example.

Also, depending on the type, size, and rate of change of data structures on the source it is possible that {project-title} cannot keep up with the change stream.
For example if a big set is repeatedly updated, {project-title} will need to read the whole set on each update and transfer it over to the target database.
With a big-enough set, {project-title} could fall behind and the internal queue could fill up leading up to updates being dropped.
Some preliminary sizing using Redis statistics and `bigkeys`/`memkeys` is recommended for these migrations.
If you need assistance please contact your Redis account team.
====

[[_replicate_dump_and_restore]]
=== Dump & Restore

The default replication mechanism in {project-title} is DUMP & RESTORE:

image::dump-and-restore.svg[]

1. Scan for keys in the source Redis database.
If live replication is enabled the reader also subscribes to keyspace notifications to generate a continuous stream of keys.

2. Reader threads iterate over the keys to read corresponding values (DUMP) and TTLs.

3. Reader threads enqueue key/value/TTL tuples into the reader queue, from which the writer dequeues key/value/TTL tuples and writes them to the target Redis database by calling RESTORE and EXPIRE.


[[_replicate_type_based]]
=== Type-Based Replication

{project-title} includes another replication strategy called *Type-Based Replication* in case the target Redis database does not support the RESTORE command (for example {link_redis_crdb}).
With this strategy each type of Redis data structure has a corresponding pair of read/write commands:

[%header,cols="h,1,1"]
|=========================================================
|Type|Read|Write

|Hash|HGETALL|HSET
|List|LRANGE|RPUSH
|Set|SMEMBERS|SADD
|Sorted Set|ZRANGE|ZADD
|Stream|XRANGE|XADD
|String|GET|SET

|=========================================================

To select this replication mechanism use the `--type ds` option:

.Type-based, live replication example
[source]
----
include::{testdir}/replicate-ds-live[]
----

WARNING: This replication strategy is more intensive in terms of CPU, memory, and network for the machines running {project-title}.
Adjust number of threads, batch, and queue sizes accordingly.

include::{includedir}/elasticache.adoc[leveloffset=+2]
