[[_usage]]
= Usage

== Install

{project-title} can be installed in different ways depending on your environment and preference.

[[_macos_install]]
=== Homebrew (macOS)

[source]
----
brew install redis-developer/tap/riot
----

[[_windows_install]]
=== Scoop (Windows)

[source]
----
scoop bucket add redis-developer https://github.com/redis-developer/scoop.git
scoop install riot
----

[[_standalone_install]]
=== Standalone (Linux)

Download the pre-compiled standalone binary `riot-standalone-{project-version}-linux-*.zip` from {link_riot_release}, uncompress and copy to the desired location.

[NOTE]
====
`riot-standalone-{project-version}-linux-*.zip` includes its own Java runtime and can be used without a previous installation of Java.
====

[[_universal_install]]
=== Universal (All)

Download the Universal {link_riot_release}, unzip, and copy to the desired location.

Launch the `bin/riot` script and follow the usage information provided.

[NOTE]
====
`riot-{project-version}.zip` requires Java 11 or greater to be installed.
====

==== Java on Ubuntu

The easiest option is to use the version packaged with Ubuntu.

First, update the package index:

[source]
----
sudo apt update
----

Next, check if Java is already installed:

[source]
----
java -version
----
 
If Java is not currently installed, you’ll see the following output:

[source]
----
Command 'java' not found, but can be installed with:

sudo apt install default-jre
sudo apt install openjdk-11-jre-headless
sudo apt install openjdk-8-jre-headless
----

Execute the following command to install the default Java Runtime Environment (JRE), which will install the JRE from OpenJDK 11:

[source]
----
sudo apt install default-jre
----
 
Verify the installation with:

[source]
----
java -version
----
 
You should see output similar to the following:

[source]
----
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing))
----

[[_docker_install]]
=== Docker

[source]
----
docker run fieldengineering/riot [OPTIONS] [COMMAND]
----

== Run

You can launch {project-title} with the following command:

[source]
----
riot
----

This will show usage help, which you can also get by running:

[source]
----
riot --help
----

[TIP]
====
You can use `--help` on any command and subcommand:

[source]
----
riot command --help
riot command subcommand --help
----
====

[[_riot_commands]]
=== Commands
{project-title} includes the following commands:

<<_db_import,`db-import`>>:: Import from a relational database.
<<_db_export,`db-export`>>:: Export Redis data to a relational database.
<<_dump_import,`dump-import`>>:: Import Redis data files into Redis.
<<_file_import,`file-import`>>:: Import from CSV/JSON/XML files.
<<_file_export,`file-export`>>:: Export Redis data to JSON or XML files.
<<_faker_import,`faker-import`>>:: Import from Faker.
<<_generate,`generate`>>:: Generate data structures.
<<_replicate,`replicate`>>:: Replicate a Redis database into another Redis database.
<<_ping,`ping`>>:: Test connectivity to a Redis database.
`generate-completion`:: Generate bash/zsh completion script for `riot`.

[[_general_options]]
=== General options
`-d, --debug`:: Log in debug mode (includes normal stacktrace).
`-H, --help`:: Show this help message and exit.
`-i, --info`:: Set log level to info.
`-q, --quiet`:: Log errors only.
`--stacktrace`:: Print out the stacktrace for all exceptions.
`-V, --version`:: Print version information and exit.
`-w, --warn`:: Set log level to warn.

[[_redis_connection_options]]
=== Redis connection options
include::{includedir}/redis-connection-options.adoc[leveloffset=+2]

[[_job_options]]
=== Job options
include::{includedir}/job-options.adoc[leveloffset=+2]

[[_generate_completion]]
=== Generate completion

[source]
----
$ riot generate-completion --help
RIOT is a data import/export tool for Redis.

Usage: riot generate-completion [-hV]
Generate bash/zsh completion script for riot.
Run the following command to give `riot` TAB completion in the current shell:

  source <(riot generate-completion)

Options:
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.

Documentation found at https://developer.redis.com/riot
----