= RIOT
:source-highlighter: highlightjs

Redis Input/Output Tool (RIOT) is a data import/export tool for Redis and RediSearch. It supports the following data sources:

* Databases through JDBC
* Delimited files (CSV)
* Fixed width files
* JSON files
* Data generator using https://github.com/DiUS/java-faker[Faker]

== Installation
Download the https://github.com/Redislabs-Solution-Architects/riot/releases/latest[latest RIOT distribution] (zip or tar.gz) and unpack the downloaded archive.

== Running
Use the `riot` script (`riot.bat` for Windows) to launch RIOT. 

== Usage
Follow the usage help provided with the `--help` option. 

== Examples

=== Importing CSV Files

Here is an excerpt of https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat[airports.dat] available at https://github.com/jpatokal/openflights[openflights]
----
1,"Goroka Airport","Goroka","Papua New Guinea","GKA","AYGA",-6.081689834590001,145.391998291,5282,10,"U","Pacific/Port_Moresby","airport","OurAirports"
2,"Madang Airport","Madang","Papua New Guinea","MAG","AYMD",-5.20707988739,145.789001465,20,10,"U","Pacific/Port_Moresby","airport","OurAirports"
3,"Mount Hagen Kagamuga Airport","Mount Hagen","Papua New Guinea","HGU","AYMH",-5.826789855957031,144.29600524902344,5388,10,"U","Pacific/Port_Moresby","airport","OurAirports"
----

.Import airports into a geoset
[source,shell]
----
riot import csv --url https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat --fields AirportID Name City Country IATA ICAO Latitude Longitude Altitude Timezone DST Tz Type Source geo --keyspace airportgeo --fields AirportID --longitude-field Longitude --latitude-field Latitude
----
.Query the `airportgeo` geoset using redis-cli
[source,shell]
----
GEORADIUS airportgeo -122.4194 37.7749 20 mi
1) "3469"
2) "10360"
3) "8982"
4) "9071"
5) "3453"

HGETALL airport:3469
 1) "AirportID"
 2) "3469"
 3) "ICAO"
 4) "KSFO"
 5) "Latitude"
 6) "37.61899948120117"
 7) "IATA"
 8) "SFO"
 9) "Longitude"
10) "-122.375"
11) "DST"
12) "A"
13) "Name"
14) "San Francisco International Airport"
15) "City"
16) "San Francisco"
17) "Type"
18) "airport"
19) "Source"
20) "OurAirports"
21) "Country"
22) "United States"
23) "Timezone"
24) "-8"
25) "Tz"
26) "America/Los_Angeles"
27) "Altitude"
28) "13"
----

=== Importing JSON Files

Here is an excerpt of beers.json available at https://github.com/rethinkdb/beerthink/blob/master/data/beers.json[beerthink]:
[source,json]
----
[
	{
		"id": "1",
		"brewery_id": "812",
		"name": "Hocus Pocus",
		"abv": "4.5",
		"ibu": "0",
		"srm": "0",
		"upc": "0",
		"filepath": "",
		"descript": "Our take on a classic summer ale.  A toast to weeds, rays, and summer haze.  A light, crisp ale for mowing lawns, hitting lazy fly balls, and communing with nature, Hocus Pocus is offered up as a summer sacrifice to clodless days.\n\nIts malty sweetness finishes tart and crisp and is best apprediated with a wedge of orange.",
		"add_user": "0",
		"last_mod": "2010-07-22 20:00:20 UTC",
		"style_name": "Light American Wheat Ale or Lager",
		"cat_name": "Other Style"
	},
	{
		"id": "6",
		"brewery_id": "1385",
		"name": "Winter Warmer",
		"abv": "5.199999809265137",
		"ibu": "0",
		"srm": "0",
		"upc": "0",
		"filepath": "",
		"descript": "",
		"add_user": "0",
		"last_mod": "2010-07-22 20:00:20 UTC",
		"style_name": "Old Ale",
		"cat_name": "British Ale"
	},
	...
]
----

* Import beers into Hashes
[source,shell]
----
riot import json --url https://raw.githubusercontent.com/rethinkdb/beerthink/master/data/beers.json hash --keyspace beers --keys id
----

* Import beers to RediSearch
+
.Create an index with redis-cli
+
[source,shell]
----
FT.CREATE beerIdx SCHEMA abv NUMERIC SORTABLE id TAG name TEXT PHONETIC dm:en style_name TEXT PHONETIC dm:en brewery_id TAG
----
.Import data into the index
+
[source,shell]
----
riot import json --url https://raw.githubusercontent.com/rethinkdb/beerthink/master/data/beers.json search --index beerIdx --keys id
----

