= RIOT
// Settings
:idprefix:
:idseparator: -
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::env-github[:icons: font]
// URIs
:project-repo: Redislabs-Solution-Architects/riot
:repo-url: https://github.com/{project-repo}
// GitHub customization
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

RIOT is a set of import/export tools for Redis:

* *riot-file*: file import/export (CSV, FW, JSON, XML)
* *riot-db*: relational databases
* *riot-redis*: data replication between Redis databases
* *riot-gen*: generate random datasets

== Getting Started

=== Download and Run

Download the {repo-url}/releases/latest[latest release] and untar/unzip the archive.

Launch the `bin/riot-*` script and follow the usage information provided.

=== Install via Homebrew

```
❯ brew install jruaux/tap/riot-db
❯ brew install jruaux/tap/riot-file
❯ brew install jruaux/tap/riot-gen
❯ brew install jruaux/tap/riot-redis
```

=== Tab Completion

RIOT has command line completion in Bash or ZSH Unix shells. The Unix shell will complete a command or option when users type the first few letters then press the TAB key.

Run the following command to install completion:
[source,shell]
----
❯ source <(riot-file generate-completion)
----

== Documentation

https://redislabs-solution-architects.github.io/riot/index.html[RIOT Documentation]