:linkattrs:
:project-owner:   redis
:project-name:    riot
:project-group:   com.redis
:project-version: 4.3.0
:project-title:   RIOT

image::docs/guide/src/docs/resources/images/riot.svg[RIOT]

---

[IMPORTANT]
====
*⚠️ This project is no longer maintained.*

RIOT has been superseded by https://github.com/redis/riotx-dist[*RIOT-X*], an enterprise-grade version with enhanced features and active support from Redis, Inc.

* *For new projects:* Please use https://redis.github.io/riotx/[RIOT-X]
* *Existing users:* You can continue using RIOT, but no new features or bug fixes will be provided
* *Support:* All support requests should be directed to the RIOT-X project

https://github.com/redis/riotx-dist[→ Go to RIOT-X on GitHub]
====

---

Get data in and out of Redis with link:http://redis.github.io/riot/[{project-title}]!

Redis Input/Output Tools ({project-title}) is a command-line utility designed to help you get data in and out of Redis.

It supports many different sources and targets:

* Relational databases
* Files (CSV, JSON, XML)
* Data generators (Redis data structures, Faker)
* and Redis itself with live and/or snapshot replication.

== Documentation

link:http://redis.github.io/riot/[redis.github.io/riot]

== Support

*This project is no longer actively maintained.*

For support, please use https://github.com/redis/riotx-dist[RIOT-X], the actively maintained successor to this project.

Existing issues will remain open for historical reference, but new issues and pull requests will not be addressed.

== Badges

image:https://github.com/{project-owner}/{project-name}/actions/workflows/early-access.yml/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions/workflows/early-access.yml"]
image:https://img.shields.io/github/release/{project-owner}/{project-name}.svg["Latest", link="https://github.com/{project-owner}/{project-name}/releases/latest"]
image:https://codecov.io/gh/{project-owner}/{project-name}/graph/badge.svg?token=bwm6gyXU0v["Coverage", link="https://codecov.io/gh/{project-owner}/{project-name}"]

== License

{project-title} is licensed under the Apache 2.0 License.
Copyright (C) 2023 Redis, Inc.
