== ReCharge
ReCharge is a bulk loader for Redis. It supports the following data
sources as inputs:

* Databases (JDBC)
* Files
** Delimited (CSV)
** Fixed width (FW)
** JSON
** XML
* https://github.com/DiUS/java-faker[Faker]

=== Building
Build each project first before you build recharge:

[source,bash]
----
git clone https://github.com/Redislabs-Solution-Architects/recharge.git
cd recharge
mvn clean install
----

=== Running

Run ReCharge using java -jar:

[source,bash]

----
$ java -jar target/recharge.jar
----

=== Parameters
Use the following parameters to configure ReCharge:

==== Redis
* `host`: Redis database hostname e.g. `--host=redis.redislabs.com`
* `port`: Redis database port e.g. `--port=12000`
* `password`: Redis database password e.g. `--password=1234`
* `timeout`: Command timeout for synchronous command execution e.g. `--timeout=5s`
* `pool.max-active`: Maximum number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
* `pool.max-idle`: Maximum number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
* `pool.min-idle`: Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
* `pool.max-wait`: Maximum amount of time a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely. e.g. `--pool.max-wait=5s`

=== Examples

The link:./examples[examples] folder contains a few sample
configurations to import various datasets:

* https://openflights.org/data.html[openflights.org]

Airlines::
  `java -jar target/recharge.jar --spring.config.location=examples/file/airlines.yml`
Airports::
  `java -jar target/recharge.jar --spring.config.location=examples/file/airports.yml`
Planes::
  `java -jar target/recharge.jar --spring.config.location=examples/file/planes.yml`
Routes::
  `java -jar target/recharge.jar --spring.config.location=examples/file/routes.yml`
