= RIOT
// Settings
:idprefix:
:idseparator: -
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
endif::[]
ifndef::env-github[:icons: font]
// URIs
:project-repo: Redislabs-Solution-Architects/riot
:repo-url: https://github.com/{project-repo}
// GitHub customization
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

RIOT is a data import/export tool for Redis and Redis Modules that connects to files, databases, and data generators.

== Getting Started

=== Homebrew  

```
$ brew install jruaux/tap/riot
$ riot --help
```

=== Download and run 

Download the {repo-url}/releases/latest[latest RIOT distribution] and untar the downloaded archive.

Launch the `riot` script (`riot.bat` for Windows) and follow the usage information provided.

=== Build and run

[subs="attributes"]
----
$ git clone {repo-url}/riot.git
$ cd riot
$ ./riot --help
----

== Shell completion

RIOT has command line completion for Bash and ZSH Unix shells:

```
$ riot <TAB><TAB>
console       db-import     file-export   gen           ping                                              
db-export     faker         file-import   info          redis-export                       
```      

=== Homebrew

The completion script is already installed and can be loaded in ZSH using:

```
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
. /usr/local/share/zsh/site-functions/_riot
```

To make this permanent, add the previous lines to `~/.zshrc`.

=== Manual installation

This requires `bash-completion` installed.

Generate the completion script and place it in `bash_completion.d`:
```
riot --completion-script > /etc/bash_completion.d/riot_completion
```

Source your `~/.bash_profile` or launch a new terminal to start using this completion script.

== Documentation

https://redislabs-solution-architects.github.io/riot/index.html[RIOT Documentation]
