= RIOT
// Settings
:idprefix:
:idseparator: -
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::env-github[:icons: font]
// URIs
:project-repo: Redislabs-Solution-Architects/riot
:repo-url: https://github.com/{project-repo}
:imagesdir: docs/images
:site-base-url: https://redislabs-solution-architects.github.io/riot/
// GitHub customization
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:caution-caption: :fire:
:important-caption: :heavy_exclamation_mark:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Badges
ifdef::badges[]
image:https://img.shields.io/github/license/Redislabs-Solution-Architects/riot.svg["License", link="https://github.com/Redislabs-Solution-Architects/riot"]
image:https://img.shields.io/github/release/Redislabs-Solution-Architects/riot.svg["Latest", link="https://github.com/Redislabs-Solution-Architects/riot/releases/latest"]
image:https://github.com/Redislabs-Solution-Architects/riot/workflows/CI/badge.svg["Actions", link="https://github.com/Redislabs-Solution-Architects/riot/workflows/CI/badge.svg"]
image:https://snyk.io/test/github/Redislabs-Solution-Architects/riot/badge.svg?targetFile=build.gradle["Known Vulnerabilities", link="https://snyk.io/test/github/Redislabs-Solution-Architects/riot?targetFile=build.gradle"]
endif::[]

[quote]
Get data in and out of Redis

image:riot.svg[RIOT,width=800]

Redis Input/Output Tools (RIOT) is a set of import/export command line utilities for Redis:

* {site-base-url}/riot-gen.html[RIOT Gen]: generate sample Redis datasets for new feature development and proof of concept.
* {site-base-url}/riot-db.html[RIOT DB]: migrate from an RDBMS to Redis, RediSearch, RedisJSON, ...
* {site-base-url}/riot-file.html[RIOT File]: bulk import/export data from/to files.
* {site-base-url}/riot-redis.html[RIOT Redis]: live replication from any Redis database (including AWS Elasticache) to another Redis database.