'\" t
.\"     Title: riot-gen-ftsugadd
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-03-11
.\"    Manual: Riot Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "RIOT\-GEN\-FTSUGADD" "1" "2020-03-11" "" "Riot Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
riot\-gen\-ftsugadd \- Add suggestion strings to an auto\-complete suggestion dictionary
.SH "SYNOPSIS"
.sp
\fBriot gen ftsugadd\fP [OPTIONS]
.SH "DESCRIPTION"
.sp
Add suggestion strings to an auto\-complete suggestion dictionary
.SH "OPTIONS"
.sp
\fB\-\-default\-score\fP=\fI<num>\fP
.RS 4
Score when field not present (default: 1.0)
.RE
.sp
\fB\-\-help\fP
.RS 4
Show this help message and exit
.RE
.sp
\fB\-\-increment\fP
.RS 4
Use increment to set value
.RE
.sp
\fB\-k\fP, \fB\-\-keys\fP=\fI<names>\fP...
.RS 4
Key fields
.RE
.sp
\fB\-p\fP, \fB\-\-keyspace\fP=\fI<str>\fP
.RS 4
Keyspace prefix
.RE
.sp
\fB\-\-payload\fP=\fI<field>\fP
.RS 4
Name of the field containing the payload
.RE
.sp
\fB\-\-score\fP=\fI<field>\fP
.RS 4
Name of the field to use for scores
.RE
.sp
\fB\-\-separator\fP=\fI<str>\fP
.RS 4
Key separator (default: :)
.RE
.sp
\fB\-\-string\fP=\fI<field>\fP
.RS 4
Field containing the suggestion
.RE