'\" t
.\"     Title: riot-db-export
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-03-11
.\"    Manual: Riot Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "RIOT\-DB\-EXPORT" "1" "2020-03-11" "" "Riot Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
riot\-db\-export \- Export to a database
.SH "SYNOPSIS"
.sp
\fBriot db\-export\fP [OPTIONS]
.SH "DESCRIPTION"
.sp
Export to a database
.SH "OPTIONS"
.sp
\fB\-b\fP, \fB\-\-batch\fP=\fI<size>\fP
.RS 4
Number of items in each batch (default: 50)
.RE
.sp
\fB\-\-help\fP
.RS 4
Show this help message and exit
.RE
.sp
\fB\-m\fP, \fB\-\-max\fP=\fI<count>\fP
.RS 4
Max number of items to read
.RE
.sp
\fB\-\-progress\fP=\fI<ms>\fP
.RS 4
Progress reporting interval (default: 300 ms)
.RE
.sp
\fB\-\-sleep\fP=\fI<ms>\fP
.RS 4
Sleep duration in millis between reads
.RE
.sp
\fB\-\-threads\fP=\fI<count>\fP
.RS 4
Thread count (default: 1)
.RE
.sp
\fB\-\-transfer\-max\-wait\fP=\fI<ms>\fP
.RS 4
Max duration to wait for transfer to complete
.RE
.SH "REDIS READER OPTIONS"
.sp
\fB\-\-count\fP=\fI<int>\fP
.RS 4
Number of elements to return for each scan call
.RE
.sp
\fB\-\-index\fP=\fI<name>\fP
.RS 4
Index name
.RE
.sp
\fB\-\-keys\fP=\fI<names>\fP...
.RS 4
Key fields
.RE
.sp
\fB\-\-keyspace\fP=\fI<str>\fP
.RS 4
Redis keyspace prefix
.RE
.sp
\fB\-\-num\fP=\fI<count>\fP
.RS 4
Limit results to number (default: 10)
.RE
.sp
\fB\-\-offset\fP=\fI<count>\fP
.RS 4
Limit results to offset (default: 0)
.RE
.sp
\fB\-\-query\fP=\fI<string>\fP
.RS 4
Search query (default: *)
.RE
.sp
\fB\-\-separator\fP=\fI<str>\fP
.RS 4
Redis key separator (default: :)
.RE
.SH "DATABASE WRITER OPTIONS"
.sp
\fB\-\-driver\fP=\fI<class>\fP
.RS 4
Fully qualified name of the JDBC driver
.RE
.sp
\fB\-n\fP, \fB\-\-username\fP=\fI<string>\fP
.RS 4
Login username of the database
.RE
.sp
\fB\-\-no\-assert\-updates\fP
.RS 4
Disable insert verification
.RE
.sp
\fB\-\-password\fP[=\fI<pwd>\fP]
.RS 4
Login password of the database
.RE
.sp
\fB\-\-sql\fP=\fI<sql>\fP
.RS 4
Insert SQL statement
.RE
.sp
\fB\-u\fP, \fB\-\-url\fP=\fI<string>\fP
.RS 4
URL to connect to the database
.RE
.SH "PROCESSOR OPTIONS"
.sp
\fB\-\-date\-format\fP=\fI<string>\fP
.RS 4
Java date format (default: M/d/yy, h:mm a)
.RE
.sp
\fB\-\-language\fP=\fI<name>\fP
.RS 4
Script language (default: ECMAScript)
.RE
.sp
\fB\-\-proc\fP=\fI<name=exp>\fP...
.RS 4
SpEL expression to process a field
.RE
.sp
\fB\-\-regex\fP=\fI<src=exp>\fP...
.RS 4
Extract fields from source field using regex
.RE
.sp
\fB\-\-script\fP=\fI<script>\fP
.RS 4
Use an inline script to process items
.RE
.sp
\fB\-\-script\-file\fP=\fI<file>\fP
.RS 4
Use an external script to process items
.RE
.sp
\fB\-\-var\fP=\fI<v=exp>\fP...
.RS 4
Register a variable in the processor context
.RE