'\" t
.\"     Title: riot-test
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-03-11
.\"    Manual: Riot Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "RIOT\-TEST" "1" "2020-03-11" "" "Riot Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
riot\-test \- Execute a test
.SH "SYNOPSIS"
.sp
\fBriot test\fP [OPTIONS]
.SH "DESCRIPTION"
.sp
Execute a test
.SH "OPTIONS"
.sp
\fB\-\-help\fP
.RS 4
Show this help message and exit
.RE
.sp
\fB\-\-latency\-distribution\fP
.RS 4
Show latency distribution
.RE
.sp
\fB\-\-latency\-iterations\fP=\fI<count>\fP
.RS 4
Number of iterations for latency test (default: 1000)
.RE
.sp
\fB\-\-latency\-sleep\fP=\fI<ms>\fP
.RS 4
Sleep duration in milliseconds between calls (default: 1)
.RE
.sp
\fB\-\-latency\-unit\fP=\fI<unit>\fP
.RS 4
Latency unit (default: MILLISECONDS)
.RE
.sp
\fB\-t\fP, \fB\-\-test\fP=\fI<name>\fP
.RS 4
Test to execute: info, ping, latency (default: ping)
.RE