'\" t
.\"     Title: riot-gen-geoadd
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-03-11
.\"    Manual: Riot Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "RIOT\-GEN\-GEOADD" "1" "2020-03-11" "" "Riot Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
riot\-gen\-geoadd \- Add geospatial items to specified keys
.SH "SYNOPSIS"
.sp
\fBriot gen geoadd\fP [OPTIONS]
.SH "DESCRIPTION"
.sp
Add geospatial items to specified keys
.SH "OPTIONS"
.sp
\fB\-\-help\fP
.RS 4
Show this help message and exit
.RE
.sp
\fB\-k\fP, \fB\-\-keys\fP=\fI<names>\fP...
.RS 4
Key fields
.RE
.sp
\fB\-\-lat\fP=\fI<field>\fP
.RS 4
Latitude field
.RE
.sp
\fB\-\-lon\fP=\fI<field>\fP
.RS 4
Longitude field
.RE
.sp
\fB\-\-member\-keyspace\fP=\fI<str>\fP
.RS 4
Keyspace prefix for member IDs
.RE
.sp
\fB\-\-members\fP=\fI<names>\fP...
.RS 4
Fields composing member IDs for collections: list geo set zset
.RE
.sp
\fB\-p\fP, \fB\-\-keyspace\fP=\fI<str>\fP
.RS 4
Keyspace prefix
.RE
.sp
\fB\-\-separator\fP=\fI<str>\fP
.RS 4
Key separator (default: :)
.RE