'\" t
.\"     Title: riot-redis-import-xadd
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-03-11
.\"    Manual: Riot Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "RIOT\-REDIS\-IMPORT\-XADD" "1" "2020-03-11" "" "Riot Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
riot\-redis\-import\-xadd \- Append entries to a stream
.SH "SYNOPSIS"
.sp
\fBriot redis\-import xadd\fP [OPTIONS]
.SH "DESCRIPTION"
.sp
Append entries to a stream
.SH "OPTIONS"
.sp
\fB\-\-help\fP
.RS 4
Show this help message and exit
.RE
.sp
\fB\-\-id\fP=\fI<field>\fP
.RS 4
Field used for stream entry IDs
.RE
.sp
\fB\-k\fP, \fB\-\-keys\fP=\fI<names>\fP...
.RS 4
Key fields
.RE
.sp
\fB\-\-maxlen\fP=\fI<int>\fP
.RS 4
Limit stream to maxlen entries
.RE
.sp
\fB\-p\fP, \fB\-\-keyspace\fP=\fI<str>\fP
.RS 4
Keyspace prefix
.RE
.sp
\fB\-\-separator\fP=\fI<str>\fP
.RS 4
Key separator (default: :)
.RE
.sp
\fB\-\-trim\fP
.RS 4
Use efficient trimming (~ flag)
.RE