'\" t
.\"     Title: riot-redis-import
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-03-11
.\"    Manual: Riot Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "RIOT\-REDIS\-IMPORT" "1" "2020-03-11" "" "Riot Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
riot\-redis\-import \- Import from Redis
.SH "SYNOPSIS"
.sp
\fBriot redis\-import\fP [OPTIONS] [COMMAND]
.SH "DESCRIPTION"
.sp
Import from Redis
.SH "OPTIONS"
.sp
\fB\-\-api\fP=\fI<name>\fP
.RS 4
API: Async, Reactive, Sync (default: Async)
.RE
.sp
\fB\-\-auth\fP[=\fI<pwd>\fP]
.RS 4
Database login password
.RE
.sp
\fB\-b\fP, \fB\-\-batch\fP=\fI<size>\fP
.RS 4
Number of items in each batch (default: 50)
.RE
.sp
\fB\-\-client\fP=\fI<name>\fP
.RS 4
Redis client name (default: picocli\-redis)
.RE
.sp
\fB\-\-cluster\fP
.RS 4
Connect to a Redis cluster
.RE
.sp
\fB\-\-command\-timeout\fP=\fI<s>\fP
.RS 4
Timeout for sync command execution (default: 60)
.RE
.sp
\fB\-\-comp\-threads\fP=\fI<int>\fP
.RS 4
Number of computation threads (default: 4)
.RE
.sp
\fB\-\-connect\-timeout\fP=\fI<ms>\fP
.RS 4
Connect timeout (default: 2000)
.RE
.sp
\fB\-\-db\fP=\fI<int>\fP
.RS 4
Redis database number
.RE
.sp
\fB\-\-driver\fP=\fI<name>\fP
.RS 4
Redis driver: Jedis, Lettuce (default: Lettuce)
.RE
.sp
\fB\-\-help\fP
.RS 4
Show this help message and exit
.RE
.sp
\fB\-\-io\-threads\fP=\fI<int>\fP
.RS 4
Number of threads for I/O operations (default: 4)
.RE
.sp
\fB\-\-ks\fP=\fI<file>\fP
.RS 4
Path to keystore
.RE
.sp
\fB\-\-ks\-password\fP[=\fI<pwd>\fP]
.RS 4
Keystore password
.RE
.sp
\fB\-m\fP, \fB\-\-max\fP=\fI<count>\fP
.RS 4
Max number of items to read
.RE
.sp
\fB\-\-max\-idle\fP=\fI<int>\fP
.RS 4
Max idle connections; \-1 for no limit (default: 8)
.RE
.sp
\fB\-\-max\-redirects\fP=\fI<int>\fP
.RS 4
Max cluster redirects (default: 5)
.RE
.sp
\fB\-\-max\-total\fP=\fI<int>\fP
.RS 4
Max connections; \-1 for no limit (default: 8)
.RE
.sp
\fB\-\-max\-wait\fP=\fI<ms>\fP
.RS 4
Max duration; \-1 for infinite (default: \-1)
.RE
.sp
\fB\-\-metrics\fP
.RS 4
Show metrics
.RE
.sp
\fB\-\-min\-idle\fP=\fI<int>\fP
.RS 4
Min idle connections (default: 0)
.RE
.sp
\fB\-\-no\-auto\-reconnect\fP
.RS 4
Disable auto\-reconnect
.RE
.sp
\fB\-\-progress\fP=\fI<ms>\fP
.RS 4
Progress reporting interval (default: 300 ms)
.RE
.sp
\fB\-\-publish\-on\-sched\fP
.RS 4
Enable publish on scheduler (default: false)
.RE
.sp
\fB\-\-request\-queue\fP=\fI<int>\fP
.RS 4
Per\-connection request queue size (default: max)
.RE
.sp
\fB\-s\fP, *\-\-servers*\fI=<s1 s2 …>\fP
.RS 4
Server endpoints (default: localhost:6379)
.RE
.sp
\fB\-\-sentinel\fP=\fI<master>\fP
.RS 4
Sentinel master
.RE
.sp
\fB\-\-sleep\fP=\fI<ms>\fP
.RS 4
Sleep duration in millis between reads
.RE
.sp
\fB\-\-socket\-timeout\fP=\fI<ms>\fP
.RS 4
Socket timeout (default: 2000)
.RE
.sp
\fB\-\-ssl\fP
.RS 4
SSL connection
.RE
.sp
\fB\-\-ssl\-provider\fP=\fI<name>\fP
.RS 4
SSL provider: Jdk, OpenSsl (default: Jdk)
.RE
.sp
\fB\-\-threads\fP=\fI<count>\fP
.RS 4
Thread count (default: 1)
.RE
.sp
\fB\-\-transfer\-max\-wait\fP=\fI<ms>\fP
.RS 4
Max duration to wait for transfer to complete
.RE
.sp
\fB\-\-ts\fP=\fI<file>\fP
.RS 4
Path to truststore
.RE
.sp
\fB\-\-ts\-password\fP[=\fI<pwd>\fP]
.RS 4
Truststore password
.RE
.SH "SOURCE REDIS OPTIONS"
.sp
\fB\-\-count\fP=\fI<int>\fP
.RS 4
Number of elements to return for each scan call
.RE
.sp
\fB\-\-index\fP=\fI<name>\fP
.RS 4
Index name
.RE
.sp
\fB\-\-keys\fP=\fI<names>\fP...
.RS 4
Key fields
.RE
.sp
\fB\-\-keyspace\fP=\fI<str>\fP
.RS 4
Redis keyspace prefix
.RE
.sp
\fB\-\-num\fP=\fI<count>\fP
.RS 4
Limit results to number (default: 10)
.RE
.sp
\fB\-\-offset\fP=\fI<count>\fP
.RS 4
Limit results to offset (default: 0)
.RE
.sp
\fB\-\-query\fP=\fI<string>\fP
.RS 4
Search query (default: *)
.RE
.sp
\fB\-\-separator\fP=\fI<str>\fP
.RS 4
Redis key separator (default: :)
.RE
.SH "PROCESSOR OPTIONS"
.sp
\fB\-\-date\-format\fP=\fI<string>\fP
.RS 4
Java date format (default: M/d/yy, h:mm a)
.RE
.sp
\fB\-\-language\fP=\fI<name>\fP
.RS 4
Script language (default: ECMAScript)
.RE
.sp
\fB\-\-proc\fP=\fI<name=exp>\fP...
.RS 4
SpEL expression to process a field
.RE
.sp
\fB\-\-regex\fP=\fI<src=exp>\fP...
.RS 4
Extract fields from source field using regex
.RE
.sp
\fB\-\-script\fP=\fI<script>\fP
.RS 4
Use an inline script to process items
.RE
.sp
\fB\-\-script\-file\fP=\fI<file>\fP
.RS 4
Use an external script to process items
.RE
.sp
\fB\-\-var\fP=\fI<v=exp>\fP...
.RS 4
Register a variable in the processor context
.RE
.SH "COMMANDS"
.sp
\fBevalsha\fP
.RS 4
Evaluates a script cached on the server side by its SHA1 digest
.RE
.sp
\fBexpire\fP
.RS 4
Set timeouts on keys
.RE
.sp
\fBftadd\fP
.RS 4
Adds documents to an index
.RE
.sp
\fBftsugadd\fP
.RS 4
Add suggestion strings to an auto\-complete suggestion dictionary
.RE
.sp
\fBgeoadd\fP
.RS 4
Add geospatial items to specified keys
.RE
.sp
\fBhmset\fP
.RS 4
Set hash values
.RE
.sp
\fBlpush\fP
.RS 4
Insert values at the head of a list
.RE
.sp
\fBnoop\fP
.RS 4
No operation
.RE
.sp
\fBrpush\fP
.RS 4
Insert values at the tail of a list
.RE
.sp
\fBsadd\fP
.RS 4
Add members to a set
.RE
.sp
\fBset\fP
.RS 4
Set string values
.RE
.sp
\fBxadd\fP
.RS 4
Append entries to a stream
.RE
.sp
\fBzadd\fP
.RS 4
Add members with scores to a sorted set
.RE