'\" t
.\"     Title: riot
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-03-11
.\"    Manual: Riot Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "RIOT" "1" "2020-03-11" "" "Riot Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
.sp
riot \-
.SH "SYNOPSIS"
.sp
\fBriot\fP [OPTIONS] [COMMAND]
.SH "DESCRIPTION"

.SH "OPTIONS"
.sp
\fB\-\-driver\fP=\fI<name>\fP
.RS 4
Redis driver: Jedis, Lettuce (default: Lettuce)
.RE
.sp
\fB\-s\fP, *\-\-servers*\fI=<s1 s2 …>\fP
.RS 4
Server endpoints (default: localhost:6379)
.RE
.sp
\fB\-\-sentinel\fP=\fI<master>\fP
.RS 4
Sentinel master
.RE
.sp
\fB\-\-auth\fP[=\fI<pwd>\fP]
.RS 4
Database login password
.RE
.sp
\fB\-\-db\fP=\fI<int>\fP
.RS 4
Redis database number
.RE
.sp
\fB\-\-client\fP=\fI<name>\fP
.RS 4
Redis client name (default: picocli\-redis)
.RE
.sp
\fB\-\-ssl\fP
.RS 4
SSL connection
.RE
.sp
\fB\-\-cluster\fP
.RS 4
Connect to a Redis cluster
.RE
.sp
\fB\-\-max\-redirects\fP=\fI<int>\fP
.RS 4
Max cluster redirects (default: 5)
.RE
.sp
\fB\-\-max\-total\fP=\fI<int>\fP
.RS 4
Max connections; \-1 for no limit (default: 8)
.RE
.sp
\fB\-\-min\-idle\fP=\fI<int>\fP
.RS 4
Min idle connections (default: 0)
.RE
.sp
\fB\-\-max\-idle\fP=\fI<int>\fP
.RS 4
Max idle connections; \-1 for no limit (default: 8)
.RE
.sp
\fB\-\-max\-wait\fP=\fI<ms>\fP
.RS 4
Max duration; \-1 for infinite (default: \-1)
.RE
.sp
\fB\-\-connect\-timeout\fP=\fI<ms>\fP
.RS 4
Connect timeout (default: 2000)
.RE
.sp
\fB\-\-socket\-timeout\fP=\fI<ms>\fP
.RS 4
Socket timeout (default: 2000)
.RE
.sp
\fB\-\-api\fP=\fI<name>\fP
.RS 4
API: Async, Reactive, Sync (default: Async)
.RE
.sp
\fB\-\-ks\fP=\fI<file>\fP
.RS 4
Path to keystore
.RE
.sp
\fB\-\-ks\-password\fP[=\fI<pwd>\fP]
.RS 4
Keystore password
.RE
.sp
\fB\-\-ts\fP=\fI<file>\fP
.RS 4
Path to truststore
.RE
.sp
\fB\-\-ts\-password\fP[=\fI<pwd>\fP]
.RS 4
Truststore password
.RE
.sp
\fB\-\-comp\-threads\fP=\fI<int>\fP
.RS 4
Number of computation threads (default: 4)
.RE
.sp
\fB\-\-io\-threads\fP=\fI<int>\fP
.RS 4
Number of threads for I/O operations (default: 4)
.RE
.sp
\fB\-\-command\-timeout\fP=\fI<s>\fP
.RS 4
Timeout for sync command execution (default: 60)
.RE
.sp
\fB\-\-metrics\fP
.RS 4
Show metrics
.RE
.sp
\fB\-\-publish\-on\-sched\fP
.RS 4
Enable publish on scheduler (default: false)
.RE
.sp
\fB\-\-no\-auto\-reconnect\fP
.RS 4
Disable auto\-reconnect
.RE
.sp
\fB\-\-request\-queue\fP=\fI<int>\fP
.RS 4
Per\-connection request queue size (default: max)
.RE
.sp
\fB\-\-ssl\-provider\fP=\fI<name>\fP
.RS 4
SSL provider: Jdk, OpenSsl (default: Jdk)
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Show this help message and exit.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version information and exit.
.RE
.sp
\fB\-q\fP, \fB\-\-quiet\fP
.RS 4
Disable all logging
.RE
.sp
\fB\-v\fP, \fB\-\-verbose\fP
.RS 4
Enable verbose logging
.RE
.sp
\fB\-d\fP, \fB\-\-debug\fP
.RS 4
Enable debug logging
.RE
.sp
\fB\-\-dns\-ttl\fP=\fI<sec>\fP
.RS 4
DNS cache TTL
.RE
.sp
\fB\-\-dns\-neg\-ttl\fP=\fI<sec>\fP
.RS 4
DNS cache negative TTL
.RE
.SH "COMMANDS"
.sp
\fBfile\-import\fP
.RS 4
Import from a file
.RE
.sp
\fBfile\-export\fP
.RS 4
Export to a file
.RE
.sp
\fBdb\-import\fP
.RS 4
Import from a database
.RE
.sp
\fBdb\-export\fP
.RS 4
Export to a database
.RE
.sp
\fBredis\-import\fP
.RS 4
Import from Redis
.RE
.sp
\fBgen\fP
.RS 4
Generate data
.RE
.sp
\fBtest\fP
.RS 4
Execute a test
.RE
.sp
\fBreplicate\fP
.RS 4
Replicate a Redis database
.RE