image::architecture.svg[]

{project-title} processes data in batch fashion: a fixed number of records (batch AKA chunk) is read, processed, and written at a time.
Then the cycle is repeated until there's no more data on the source.

[[batch]]
== Batching

The default batch size is 50, which means that an execution step reads 50 items at a time from the source, processes them, and finally writes then to the target.
If the target is Redis, writing is done in a single command https://redis.io/topics/pipelining[pipeline] to minimize the number of roundtrips to the server.

You can change the batch size (and hence pipeline size) using the `--batch` option.
The optimal batch size in terms of processing throughput depends on a few factors like record size and command types (see https://stackoverflow.com/a/32165090[here] for details).

[[threads]]
== Multi-threading

It is possible to parallelize processing by using multiple threads.
In that configuration, each chunk of items is read, processed, and written in a separate thread of execution.

To set the number of threads use the `--threads` option.