= {app-name}
:app-name: RIOT DB
:connector: db
:app: riot-db
include::../../core/src/docs/asciidoc/preamble.adoc[]

{app-name} lets you import and export data from relational databases.

include::../../core/src/docs/asciidoc/getting_started.adoc[]

== Drivers

{app-name} includes drivers for the most common RDBMSs:

* https://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/OracleDriver.html[Oracle]
+
`jdbc:oracle:thin:@myhost:1521:orcl`

* https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.java.doc/src/tpc/imjcc_r0052342.html[IBM Db2]
+
`jdbc:db2://host:port/database`

* https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-2017[MS SQL Server]
+
`jdbc:sqlserver://[serverName[\instanceName][:portNumber]][;property=value[;property=value]]`

* https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html[MySQL]
+
`jdbc:mysql://[host]:[port][/database][?properties]`

* https://www.postgresql.org/docs/7.4/jdbc-use.html[PostgreSQL]
+
`jdbc:postgresql://host:port/database`

* https://www.sqlitetutorial.net/sqlite-java/sqlite-jdbc-driver/[SQLite]
+
`jdbc:sqlite:sqlite_database_file_path`

[TIP]
====
For non-included databases you must install the corresponding JDBC driver under the `lib` directory and modify the {app-name} `CLASSPATH`:

* *nix: `bin/{app}` -> `CLASSPATH=$APP_HOME/lib/myjdbc.jar:$APP_HOME/lib/...`
* Windows: `bin\{app}.bat` -> `set CLASSPATH=%APP_HOME%\lib\myjdbc.jar;%APP_HOME%\lib\...`
====

== Importing

Use the `import` command to import the result set of a SQL statement:

[subs="attributes",source,bash]
----
{app} import --help
----

.PostgreSQL Example
[source,bash]
----
include::src/test/resources/import-postgresql[]
----

include::../../core/src/docs/asciidoc/processing.adoc[]

include::../../core/src/docs/asciidoc/redis-commands.adoc[]

== Exporting

Use the `export` command to export data from Redis to the database:

[subs="attributes",source,bash]
----
{app} export --help
----

.Export to PostgreSQL
[source,bash]
----
include::src/test/resources/export-postgresql[]
----

.Import from PostgreSQL to JSON strings
[source,bash]
----
include::src/test/resources/import-postgresql-set[]
----

This will produce Redis strings that look like this:

[source,json]
----
include::src/docs/asciidoc/order.json[]
----
