= {project-title}

== Introduction

{project-title} is a database import/export tool for Redis built on top of https://github.com/redis-developer/lettucemod/[LettuceMod]. 

It supports https://redis.io[Redis] and https://redis.com/redis-enterprise-software/overview/[Redis Enterprise] in either standalone or https://redis.io/topics/cluster-tutorial[cluster] deployments.

[[_getting-started]]
== Getting Started

include::{includedir}/_getting-started.adoc[leveloffset=+1]

== JDBC Drivers

{project-title} includes JDBC drivers for the most common RDBMSs:

* https://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/OracleDriver.html[Oracle]
+
`jdbc:oracle:thin:@myhost:1521:orcl`

* https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.java.doc/src/tpc/imjcc_r0052342.html[IBM Db2]
+
`jdbc:db2://host:port/database`

* https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-2017[MS SQL Server]
+
`jdbc:sqlserver://[serverName[\instanceName][:portNumber]][;property=value[;property=value]]`

* https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html[MySQL]
+
`jdbc:mysql://[host]:[port][/database][?properties]`

* https://www.postgresql.org/docs/7.4/jdbc-use.html[PostgreSQL]
+
`jdbc:postgresql://host:port/database`

* https://www.sqlitetutorial.net/sqlite-java/sqlite-jdbc-driver/[SQLite]
+
`jdbc:sqlite:sqlite_database_file_path`

[TIP]
====
For non-included databases you must install the corresponding JDBC driver under the `lib` directory and modify the `CLASSPATH`:

* *nix: `bin/riot-db` -> `CLASSPATH=$APP_HOME/lib/myjdbc.jar:$APP_HOME/lib/...`
* Windows: `bin\riot-db.bat` -> `set CLASSPATH=%APP_HOME%\lib\myjdbc.jar;%APP_HOME%\lib\...`
====

== Importing

The `import` command reads rows from a SQL resultset and writes them to Redis.

=== Usage

[subs="+quotes"]
----
[green]#riot-db# -h <redis host> -p <redis port> import --url <jdbc url> [olive]#SQL# [REDIS COMMAND...]
----

To show the full usage, run:

[subs="+quotes"]
----
[green]#riot-db# import --help
----

.PostgreSQL Example
[source,console]
----
include::{test-resources}/import-postgresql[]
----

=== Redis Commands

include::{includedir}/_redis-commands.adoc[leveloffset=+2]

=== Processing

include::{includedir}/_processing.adoc[leveloffset=+2]

== Exporting

The `export` command reads data from a Redis database and writes it to a SQL database.
The general usage is:
[subs="+quotes"]
----
[green]#riot-db# -h <redis host> -p <redis port> export --url <jdbc url> [olive]#SQL#
----

To show the full usage, run:
[subs="+quotes"]
----
[green]#riot-db# export --help
----

.Export to PostgreSQL
[source,console]
----
include::{test-resources}/export-postgresql[]
----

.Import from PostgreSQL to JSON strings
[source,console]
----
include::{test-resources}/import-postgresql-set[]
----

This will produce Redis strings that look like this:
[source,json]
----
include::../resources/order.json[]
----

== Architecture

include::{includedir}/_architecture.adoc[leveloffset=+1]