= {app-name}
:app-name: RIOT DB
:app: riot-db
:resources: ../connectors/db/src/test/resources
include::toc.adoc[]
include::github.adoc[]

*{app-name}* lets you import/export data from relational databases.

== Getting Started

include::getting_started.adoc[]

=== Drivers

{app-name} includes drivers for the most common RDBMSs:

* https://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/OracleDriver.html[Oracle]
+
`jdbc:oracle:thin:@myhost:1521:orcl`

* https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.java.doc/src/tpc/imjcc_r0052342.html[IBM Db2]
+
`jdbc:db2://host:port/database`

* https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-2017[MS SQL Server]
+
`jdbc:sqlserver://[serverName[\instanceName][:portNumber]][;property=value[;property=value]]`

* https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html[MySQL]
+
`jdbc:mysql://[host]:[port][/database][?properties]`

* https://www.postgresql.org/docs/7.4/jdbc-use.html[PostgreSQL]
+
`jdbc:postgresql://host:port/database`

* https://www.sqlitetutorial.net/sqlite-java/sqlite-jdbc-driver/[SQLite]
+
`jdbc:sqlite:sqlite_database_file_path`

[TIP]
====
For non-included databases you must install the corresponding JDBC driver under the `lib` directory and modify the {app-name} `CLASSPATH`:

* *nix: `bin/{app}` -> `CLASSPATH=$APP_HOME/lib/myjdbc.jar:$APP_HOME/lib/…`
* Windows: `bin\{app}.bat` -> `set CLASSPATH=%APP_HOME%\lib\myjdbc.jar;%APP_HOME%\lib\…`
====

== Importing

Use the `import` command to import the result set of a SQL statement.

=== Usage

[source,shell]
----
❯ riot-db import --help
Usage: riot-db import [OPTIONS] SQL [REDIS COMMAND]
Import from a database
      SQL                    SQL SELECT statement
  -H, --help                 Show this help message and exit.
      --[no-]progress        Show progress bars. True by default.
      --threads=<int>        Thread count (default: 1).
  -b, --batch=<size>         Number of items in each batch (default: 50).
      --max=<count>          Max number of items to read.
      --skip-limit=<int>     Max number of failed items to skip before the transfer fails (default: 0).
      --driver=<class>       Fully qualified name of the JDBC driver
      --url=<string>         JDBC URL to connect to the database
      --username=<string>    Login username of the database
      --password[=<pwd>]     Login password of the database
      --fetch=<size>         Number of rows to return with each fetch
      --rows=<count>         Max number of rows the ResultSet can contain
      --query-timeout=<ms>   The time in milliseconds for the query to timeout
      --process=<f=exp>...   SpEL processors in the form: --process field1=" <expression>" field2="<expression>" …
      --var=<v=exp>...       Register a variable in the SpEL processor context
      --date=<string>        Processor date format (default: M/d/yy, h:mm a)
      --filter=<exp>...      Discard records using SpEL boolean expressions
      --regex=<f=exp>...     Extract named values from source field using regex
Redis commands:
  eval         Evaluate a Lua script with keys and arguments from input
  expire       Set timeouts on keys
  geoadd       Add members to a geo set
  hset, hmset  Set hashes from input
  lpush        Insert values at the head of a list
  noop         No operation: accepts input and does nothing
  rpush        Insert values at the tail of a list
  sadd         Add members to a set
  set          Set strings from input
  xadd         Append entries to a stream
  zadd         Add members with scores to a sorted set
----

.PostgreSQL Example
[source,shell]
----
include::{resources}/import-postgresql[]
----

=== Processing

include::processing.adoc[]

=== Redis Commands

include::redis-commands.adoc[]

== Exporting

.Export to PostgreSQL
[source,shell]
----
include::{resources}/export-postgresql[]
----

.Import from PostgreSQL to JSON strings
[source,shell]
----
include::{resources}/import-postgresql-set[]
----

This will produce Redis strings that look like this:

[source,json]
----
include::order.json[]
----
