= {app-name}
:app-name: RIOT Gen
:app: riot-gen
:resources: ../connectors/gen/src/test/resources
include::toc.adoc[]
include::github.adoc[]

*{app-name}* is a data generator based on https://github.com/DiUS/java-faker[Faker]:

[source,shell]
----
include::{resources}/import-hset[]
----

All supported Faker data types are listed <<faker-data-types,below>>.

== Getting Started

include::getting_started.adoc[]

== Importing

=== Usage

[source,shell]
----
❯ riot-gen import --help
Usage: riot-gen import [OPTIONS] [SPEL...] [REDIS COMMAND]
Import generated data
      [SPEL...]              SpEL expressions
  -H, --help                 Show this help message and exit.
      --[no-]progress        Show progress bars. True by default.
      --threads=<int>        Thread count (default: 1).
  -b, --batch=<size>         Number of items in each batch (default: 50).
      --max=<count>          Max number of items to read.
      --skip-limit=<int>     Max number of failed items to skip before the transfer fails (default: 0).
      --introspect=<index>   Use given search index to introspect Faker fields
      --locale=<tag>         Faker locale (default: en)
      --metadata             Include metadata (index, partition)
      --start=<int>          Start index (default: 0)
      --end=<int>            End index (default: 1000)
      --sleep=<ms>           Duration in ms to sleep before each item generation (default: 0)
      --process=<f=exp>...   SpEL processors in the form: --process field1="<expression>" field2="<expression>" …
      --var=<v=exp>...       Register a variable in the SpEL processor context
      --date=<string>        Processor date format (default: M/d/yy, h:mm a)
      --filter=<exp>...      Discard records using SpEL boolean expressions
      --regex=<f=exp>...     Extract named values from source field using regex
Redis commands:
  eval         Evaluate a Lua script with keys and arguments from input
  expire       Set timeouts on keys
  geoadd       Add members to a geo set
  hset, hmset  Set hashes from input
  lpush        Insert values at the head of a list
  noop         No operation: accepts input and does nothing
  rpush        Insert values at the tail of a list
  sadd         Add members to a set
  set          Set strings from input
  xadd         Append entries to a stream
  zadd         Add members with scores to a sorted set
----

.HSET Example
[source,shell]
----
include::{resources}/import-hset[]
----

.SADD Example
[source,shell]
----
include::{resources}/import-sadd[]
----

=== Processing

include::processing.adoc[]

=== Redis Commands

include::redis-commands.adoc[]

=== Introspecting RediSearch

[source,shell]
----
include::{resources}/index-introspection[]
----

[#faker-data-types]
== Faker Fields

* *address*: buildingNumber city cityName cityPrefix citySuffix country countryCode firstName fullAddress lastName latitude longitude secondaryAddress state stateAbbr streetAddress streetAddressNumber streetName streetPrefix streetSuffix timeZone zipCode
* *ancient*: god hero primordial titan
* *animal*: name
* *app*: author name version
* *artist*: name
* *avatar*: image
* *aviation*: METAR aircraft airport
* *backToTheFuture*: character date quote
* *beer*: hop malt name style yeast
* *book*: author genre publisher title
* *bool*: bool
* *buffy*: bigBads celebrities characters episodes quotes
* *business*: creditCardExpiry creditCardNumber creditCardType
* *cat*: breed name registry
* *chuckNorris*: fact
* *code*: asin ean13 ean8 gtin13 gtin8 imei isbn10 isbn13 isbnGroup isbnGs1 isbnRegistrant
* *color*: hex name
* *commerce*: color department material price productName promotionCode
* *company*: bs buzzword catchPhrase domainName domainSuffix industry logo name profession suffix url
* *country*: capital countryCode2 countryCode3 currency currencyCode flag name
* *crypto*: md5 sha1 sha256 sha512
* *currency*: code name
* *date*: birthday
* *demographic*: demonym educationalAttainment maritalStatus race sex
* *dog*: age breed coatLength gender memePhrase name size sound
* *dragonBall*: character
* *dune*: character planet quote saying title
* *educator*: campus course secondarySchool university
* *elderScrolls*: city creature dragon firstName lastName quote race region
* *esports*: event game league player team
* *file*: extension fileName mimeType
* *finance*: bic createCountryCodeToBasicBankAccountNumberPatternMap creditCard iban randomCreditCardType
* *food*: dish fruit ingredient measurement spice sushi vegetable
* *friends*: character location quote
* *funnyName*: name
* *gameOfThrones*: character city dragon house quote
* *hacker*: abbreviation adjective ingverb noun verb
* *harryPotter*: book character location quote
* *hipster*: word
* *hitchhikersGuideToTheGalaxy*: character location marvinQuote planet quote specie starship
* *hobbit*: character location quote thorinsCompany
* *howIMetYourMother*: catchPhrase character highFive quote
* *idNumber*: invalid invalidSvSeSsn ssnValid valid validSvSeSsn
* *internet*: avatar domainName domainSuffix domainWord emailAddress image ipV4Address ipV4Cidr ipV6Address ipV6Cidr macAddress password privateIpV4Address publicIpV4Address safeEmailAddress slug url userAgentAny uuid
* *job*: field keySkills position seniority title
* *leagueOfLegends*: champion location masteries quote rank summonerSpell
* *lebowski*: actor character quote
* *lordOfTheRings*: character location
* *lorem*: character characters paragraph sentence word words
* *matz*: quote
* *medical*: diseaseName hospitalName medicineName symptoms
* *music*: chord genre instrument key
* *name*: bloodGroup firstName fullName lastName name nameWithMiddle prefix suffix title username
* *nation*: capitalCity flag language nationality
* *number*: digit randomDigit randomDigitNotZero randomNumber
* *overwatch*: hero location quote
* *phoneNumber*: cellPhone extension phoneNumber subscriberNumber
* *pokemon*: location name
* *princessBride*: character quote
* *relationships*: any direct extended inLaw parent sibling spouse
* *rickAndMorty*: character location quote
* *robin*: quote
* *rockBand*: name
* *shakespeare*: asYouLikeItQuote hamletQuote kingRichardIIIQuote romeoAndJulietQuote
* *slackEmoji*: activity celebration custom emoji foodAndDrink nature objectsAndSymbols people travelAndPlaces
* *space*: agency agencyAbbreviation company constellation distanceMeasurement galaxy meteorite moon nasaSpaceCraft nebula planet star starCluster
* *starTrek*: character location specie villain
* *stock*: nsdqSymbol nyseSymbol
* *superhero*: descriptor name power prefix suffix
* *team*: creature name sport state
* *twinPeaks*: character location quote
* *university*: name prefix suffix
* *weather*: description temperatureCelsius temperatureFahrenheit
* *witcher*: character location monster quote school witcher
* *yoda*: quote
* *zelda*: character game