The following processors can be applied to records in that order:

* Filters
* Transforms
* Regular expressions

==== Filter

Keep records that match a https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions[Spring Expression Language] (SpEL) boolean expression

`--filter "name matches '[a-zA-Z\\s]+'"`

==== Transform

Produce key/value pairs using SpEL: `field1=<exp>`, `field2=<exp>`, ...

For example `--spel field1=' generates a field named `field1` with always the same value `foo`.

Input fields are accessed by name (e.g. `field3=field1+field2`).

The processor also exposes the following variables that can be called with the `#` prefix:

* `redis` : Redis connection to issue any command, e.g. `name=#redis.hgetall('person1').lastName`
* `date` : date parser/formatter, e.g. `epoch=#date.parse(mydate).getTime()`
* `index` : sequence number of the item being generated, e.g. `id=#index`

==== Regex

Extract patterns from source fields using regular expressions:

`--regex "name=(?<first>\w+)\/(?<last>\w+)"`