The following processors can be applied to records in that order:

* Transforms
* Regular expressions
* Filters

==== Transform

Produce key/value pairs using https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions[Spring Expression Language] (SpEL): `field1=<exp>`, `field2=<exp>`, ...

For example `--process "field1='foo'"` generates a field named `field1` with always the same value `foo`.

Input fields are accessed by name (e.g. `field3=field1+field2`).

The processor also exposes the following variables that can be called with the `#` prefix:

===== redis
Redis connection to issue any command:

`--process "name=#redis.hgetall('person1').lastName"`

===== date
Date parser/formatter:

`--process "epoch=#date.parse(mydate).getTime()"`

===== index
Sequence number of the item being generated:

`--process "id=#index"`

==== Regex

Extract patterns from source fields using regular expressions:

`--regex "name=(?<first>\w+)\/(?<last>\w+)"`

==== Filter

Keep records that match a SpEL boolean expression.

`--filter "value matches '\\d+'"` will only keep records where the `value` field is a series of digits.


